### ISSUE TITLE
Linux workload creation tutorial

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#1000]
Hi,
I'm looking to create a workload for Linux but it is unclear how to deploy the tests in the target system. All the workload are mostly Android related and others are very basic like dhrystone. It is hard to figure out how to create a specific workload with binaries and dependencies. Is there any example to create a workload like glmark2?

Thanks in advance

**Comment by marcbonnici** [comment]
Hi,
Have you seen the developer section of our online documentation?

I think the relevant sections would be:
- The outline of creating a new basic workload: 
https://workload-automation.readthedocs.io/en/latest/developer_information.html#adding-a-basic-workload
- And our sections detailing how we perform resource resolution along with how to deploy them to the target:
https://workload-automation.readthedocs.io/en/latest/developer_information.html#dynamic-resource-resolution
https://workload-automation.readthedocs.io/en/latest/developer_information.html#deploying-executables-to-a-target
https://workload-automation.readthedocs.io/en/latest/developer_information.html#deploying-assets

Please let us know if anything is still unclear so we can clarify.

**Comment by dlezcano** [comment]
Ah, I missed it in the documentation. Thanks for the pointers!
