### ISSUE TITLE
Is it possible to run non-static binaries for Linux workloads?

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#1005]
Hi all,

AFAICS, all binaries are statically linked and deployed on a busybox target system.

Is it possible to run dynamically linked binaries? I'm interested in running glmark2, mplayer, phoronix test suite, etc ...

Thanks in advance

**Comment by marcbonnici** [comment]
Yes you can, there are no restrictions on the binary that can be ran enforced from WA or devlib. 
The reason that we provide statically linked binaries is to try and ensure maximum compatibility across devices rather than rely on a particular device having suitable libraries available.

**Comment by dlezcano** [comment]
Hi sorry for the delay, I messed the notifications.
Is it possible to directly invoke a pre-installed tool on the target ?

**Comment by setrofim** [comment]
Sure, `self.target.execute()` will execute an arbitrary command, so you can  invoke whatever. We tend not to rely on pre-installed tools in our code as that makes things a lot less portable and negatively impacts reproducibility of results. But in your private deployments, there is no reason why you can't invoke pre-installed tools that you know are going to be there.

**Comment by dlezcano** [comment]
Excellent. I'll give it a try, thanks!

**Comment by dlezcano** [comment]
Successfully created the workloads with the installed tools and self.target.execute().
