### ISSUE TITLE
Error(Incorrect padding): generic_linux v5.4-rc1

### ISSUE THREAD

**Issue by khilman** [ARM-software/workload-automation#1027]
I'm a new WA user trying to use it with generic_linux target running a very recent version of linux: v5.4-rc1, and I'm getting this:

```
$ wa run -f dhrystone -c meson-gxbb-p200.yaml
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing run
INFO     Initializing execution context
INFO     Connecting to target
ERROR      File "/usr/local/lib/python3.5/dist-packages/wa/framework/signal.py", line 323, in wrap
ERROR        yield
ERROR      File "/usr/local/lib/python3.5/dist-packages/wa/framework/target/manager.py", line 141, in _init_target
ERROR        self.target.connect()
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/target.py", line 273, in connect
ERROR        self._update_modules('connected')
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/target.py", line 837, in _update_modules
ERROR        self._install_module(mod, **params)
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/target.py", line 849, in _install_module
ERROR        mod.install(self, **params)
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/module/__init__.py", line 60, in install
ERROR        setattr(target, attr_name, cls(target, **params))
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/module/hwmon.py", line 137, in __init__
ERROR        self.scan()
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/module/hwmon.py", line 140, in scan
ERROR        values_tree = self.target.read_tree_values(self.root, depth=3, tar=True)
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/target.py", line 777, in read_tree_values
ERROR        strip_null_chars)
ERROR      File "/usr/local/lib/python3.5/dist-packages/devlib/target.py", line 712, in read_tree_tar_flat
ERROR        tar_gz = base64.b64decode(output)
ERROR      File "/usr/lib/python3.5/base64.py", line 88, in b64decode
ERROR        return binascii.a2b_base64(s)
ERROR    
ERROR    Error(Incorrect padding)
INFO     Done.
INFO     Run duration: N/A
INFO     Ran a total of 0 iterations: 
INFO     Results can be found in wa_output
WARNING  There were errors during execution.
WARNING  Please see wa_output/run.log
```

Attached is the run.log, and here's the device file:
```
device: "generic_linux"
device_config:
        host: 192.168.0.142
        username: workload
        password: automation
```

[run.log](https://github.com/ARM-software/workload-automation/files/3692132/run.log)

**Comment by khilman** [comment]
Same result when booting the target with v5.3 kernel

**Comment by khilman** [comment]
And FWIW, I installed WA via pip, following the quick summary documented here: https://workload-automation.readthedocs.io/en/latest/user_information.html#install

**Comment by khilman** [comment]
Ah, if I use the `root` user, the workload runs just fine.  How can I make this work without root?  I was under the impression that WA would use `sudo` on the target when root priveleges are needed.

**Comment by setrofim** [comment]
WA  _will_ try to use `sudo`, however, depending on the device security policy, that may not work for certain operations, and `root` rather than `sudoers` is allowed to perform them.

The issue you've listed above is with `hwmon` module (one of the default modules loaded by target). If you don't wish to use `root`, and don't need `hwmon`, you can disable default module loading:

```
device: "generic_linux"
device_config:
        host: 192.168.0.142
        username: workload
        password: automation
        load_default_modules: False

augmentations: [~~]   # disable default augmentations
```

You can then re-enable augmentations if/when you need them one-by-one.

**Comment by khilman** [comment]
Thanks for the pointer on disabling default augmentations.  That allowed me to run as a normal user.

Thanks for the decoding that it was an issue with the hwmon test.  It wasn't obvious to a new user from the backtrace.  Maybe improving the error catching/reporting of these things could be improved for that.

**Comment by marcbonnici** [comment]
We have improved the error reporting in https://github.com/ARM-software/devlib/pull/433/commits/77014220f16be297b943816b223f46e0709c041a to indicate which module the error originated from if initialisation fails.
