### ISSUE TITLE
Couldn't find the sha1 of the kernel

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#1028]
Hi,

I've got the following error.

The kernel uname -r returns "5.3.0-qcomlt-arm64"
It was compiled with:
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j 12 Image.gz modules dtbs KERNELRELEASE=5.3.0-qcomlt-arm64

Could it be the reason why WA is complaining about not finding a sha1?
Thanks in advance

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-783494cfd519> in <module>
     10 
     11     # Kernel tree used for the tests
---> 12     kernel_repo_path='/home/dlezcano/Linux/linux-qcomlt'
     13 )

~/lisa/lisa/wa_results_collector.py in __init__(self, base_dir, wa_dirs, plat_info, kernel_repo_path, parse_traces, use_cached_trace_metrics, display_charts)
    159         for wa_dir in wa_dirs:
    160             logger.info("Reading wa_dir %s", wa_dir)
--> 161             df_list.append(self._read_wa_dir(wa_dir))
    162         df = df.append(df_list)
    163 

~/lisa/lisa/wa_results_collector.py in _read_wa_dir(self, wa_dir)
    382         # refactoring to use WA's own API for reading output directories.
    383         df['_job_dir'] = df['id'].replace(job_dir_map)
--> 384         df.loc[:, 'kernel_sha1'] = self._wa_get_kernel_sha1(wa_dir)
    385 
    386         return df

~/lisa/lisa/utils.py in wrapper(first, *args, **kwargs)
    206                 cache_map[first] = partial
    207 
--> 208             return partial(*args, **kwargs)
    209 
    210         return wrapper

~/lisa/lisa/utils.py in partial(*args, **kwargs)
    202                 @apply_lru
    203                 def partial(*args, **kwargs):
--> 204                     return f(ref(), *args, **kwargs)
    205 
    206                 cache_map[first] = partial

~/lisa/lisa/wa_results_collector.py in _wa_get_kernel_sha1(self, wa_dir)
    591 
    592         raise RuntimeError("Couldn't find the sha1 of the kernel of the device "
--> 593                            "that produced {}".format(wa_dir))
    594 
    595     @memoized

RuntimeError: Couldn't find the sha1 of the kernel of the device that produced /var/www/wa_output/Linux/glmark2

**Comment by setrofim** [comment]
This is an issue with LISA rather than WA -- looks like LISA expects the SHA1 to be present in the kernel release version. Please raise this with LISA maintainers.

**Comment by dlezcano** [comment]
right, thanks!
