### ISSUE TITLE
How to poll the load and the temperature in different files

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#1029]
Hi,
I'm creating generic LISA file to analyze the behavior of the system. Currently the WA configuration specifies a poller file getting the temperature and depending on the board, it could be 1 sensor or 11 sensors, so the LISA script is written in such way it is able to plot the temperature figures whatever the number of the sensors.

Now I want to correlate the temperature with the load of the CPUs, there is no 1:1 relationship between a sensor and a CPU, so I can't add the load in the poller output.

Is it possible to poll into a different file? Or is there another way to do that ?

Thanks in advance

**Comment by setrofim** [comment]
I not sure what you are asking, exactly. If you're asking whether it's possible to poll a specific file/specific set of files while running a workload, then, yes, we have a `file_poller` instrument that will let you specify a path that you want to poll: https://github.com/ARM-software/workload-automation/blob/master/wa/instruments/poller/__init__.py#L28

If you're asking how to correlate temperature to CPU load, then this not really a WA question, and more to do with data analysis. There is no simple answer to this. It depends entirely on

- What your overall goal is.
- Where the sensors are located on a particular device/SoC.
- Your experimental setup.

>there is no 1:1 relationship between a sensor and a CPU, so I can't add the load in the poller output.

Per-core temperature sensors are extremely rare. Most devices will have, at most, two or three sensors positioned at arbitrary points in the SoC, vaguely in the vicinity of CPU cores, GPU, etc. 

It should also be pointed out that attempting to correlate a CPU core's load to it's temperature in isolation will not give you a complete picture. Given the proximity of cores to each other, you will find that a core's temperature is heavily impacted not only by its own load,  but also by that of its siblings (and, to a lesser extent, by what's happening on the rest of the SoC, e.g. GPU).

**Comment by dlezcano** [comment]
> I not sure what you are asking, exactly. If you're asking whether it's possible to poll a specific file/specific set of files while running a workload, then, yes, we have a `file_poller` instrument that will let you specify a path that you want to poll: https://github.com/ARM-software/workload-automation/blob/master/wa/instruments/poller/__init__.py#L28

Yeah, I'm aware of the poller instrument, this is what I have in my configurations:

db845c:
-----------

file_poller:
     files : [  '/sys/class/thermal/thermal_zone0/temp',
                '/sys/class/thermal/thermal_zone1/temp',
                '/sys/class/thermal/thermal_zone2/temp',
                '/sys/class/thermal/thermal_zone3/temp',
                '/sys/class/thermal/thermal_zone4/temp',
                '/sys/class/thermal/thermal_zone5/temp',
                '/sys/class/thermal/thermal_zone6/temp',
                '/sys/class/thermal/thermal_zone7/temp',
                '/sys/class/thermal/thermal_zone9/temp',
                '/sys/class/thermal/thermal_zone10/temp' ]
                
     labels : [ 'CPU0', 'CPU1', 'CPU2', 'CPU3', 
                'CPU4', 'CPU5', 'CPU6', 'CPU7',
                'Cluster0', 'Cluster1' ]

And for the hikey960:
----------------------------
file_poller:
     files : ['/sys/class/thermal/thermal_zone0/temp']
     labels : [ 'temp' ]

The script plotting the temperature graphics reads the number of columns and create a figure accordingly to the number of thermal zones.

Now I want to poll also the CPU load without mixing the load with the temperature in the same file.

Is it possible use the poller to store the output in different files?

> If you're asking how to correlate temperature to CPU load, then this not really a WA question, and more to do with data analysis. There is no simple answer to this. It depends entirely on
> 
> * What your overall goal is.
> * Where the sensors are located on a particular device/SoC.
> * Your experimental setup.
> 
> > there is no 1:1 relationship between a sensor and a CPU, so I can't add the load in the poller output.
> 
> Per-core temperature sensors are extremely rare. Most devices will have, at most, two or three sensors positioned at arbitrary points in the SoC, vaguely in the vicinity of CPU cores, GPU, etc.
> 
> It should also be pointed out that attempting to correlate a CPU core's load to it's temperature in isolation will not give you a complete picture. Given the proximity of cores to each other, you will find that a core's temperature is heavily impacted not only by its own load, but also by that of its siblings (and, to a lesser extent, by what's happening on the rest of the SoC, e.g. GPU).

I know that and it is precisely for this reason why I need to figure out all parameters of the SoC, the CPU load is one of them :)

**Comment by setrofim** [comment]
>Is it possible use the poller to store the output in different files?

This is not something that is supported by the poller instrument. But it's easy enough to  post-process poller output into separate files with something like

```python
#!/usr/bin/env python3
import sys
import csv

with open(sys.argv[1]) as fh:
    reader = csv.reader(fh)

    heads = next(reader)
    out_files = [csv.writer(open(f'{h}.csv', 'w')) for h in heads]

    for writer, head in zip(out_files, heads):
        writer.writerow([head])

    for writer, rows in zip(out_files, zip(*[r for r in reader])):
        writer.writerows([[r] for r in rows])
```

**Comment by dlezcano** [comment]
Hmm, that does not fit well with the script I'm writing.
May be I can use 'cpustates' utilzation-timeline.csv ?

**Comment by setrofim** [comment]
Maybe? Like I said, it depends entirely on what you are actually trying to do.

**Comment by dlezcano** [comment]
I want to plot the temperature and the cpu utilization in two different figures

**Comment by setrofim** [comment]
I that case, yes, the timeline generated by cpustates is what you want.

**Comment by dlezcano** [comment]
Great, thanks.
Is there an example somewhere how to process the cvs outputs from cpustates? The documentation gives the description but not how to use them.

**Comment by setrofim** [comment]
We don't have anything like a standard set of notebooks for this. A colleague dug up an old notebook, which we can share publicly. Please find it attached. Note that it's from a while ago, and they may have been slight format changes in the cpustates output. Also, I had to delete some cells at the beginning that had non-public references, so the code won't run as-is, but should give you some idea for how to manipulate the timeline output for visualisation.

**Comment by setrofim** [comment]
[notebook-sample.html.gz](https://github.com/ARM-software/workload-automation/files/3734541/notebook-sample.html.gz)
Actually attaching this time....

**Comment by dlezcano** [comment]
Thanks!
