### ISSUE TITLE
Improve Data Deletion from Postgres Database

### ISSUE THREAD

**Issue by marcbonnici** [ARM-software/workload-automation#1034]
We should provide guidance in our documentation to detail either how to manually delete the relevant information from each table or alternatively we should modify our schema to implement cascading deletion.  

Currently have a jupyter notebook for this purpose which if tidied up could be utilised as part of the process depending on the method we decide to go for.

**Comment by setrofim** [comment]
This has already been implemented in `v3.2.0`, right?

**Comment by marcbonnici** [comment]
No this feature has not been included as of yet.

**Comment by setrofim** [comment]
Ah, ok. My mistake.

**Comment by marcbonnici** [comment]
Implemented in https://github.com/ARM-software/workload-automation/pull/1121
