### ISSUE TITLE
Failing to connect after an update

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#1073]
Hi,
I just  updated the devlib + wa and tried to run my agenda but got this issue:

INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing run
WARNING  Depreciated parameter supplied for "telnet" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "password_prompt" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "original_prompt" in "generic_linux". The value will be ignored.
INFO     Initializing execution context
INFO     Connecting to target
ERROR    Connection lost: [Errno None] Unable to connect to port 0 on 192.168.0.32
INFO     Done.
INFO     Run duration: N/A
INFO     Ran a total of 0 iterations: 
INFO     Results can be found in /var/www/wa_output/Linux/schbench
WARNING  There were errors during execution.
WARNING  Please see /var/www/wa_output/Linux/schbench/run.log

Config content:
device: 'generic_linux'

device_config:
    host: '192.168.0.32'
    username: 'root'
    password: 'root'

**Comment by marcbonnici** [comment]
Hi,

Thanks for reporting that, I have merged a fix that should ensure we set a default port number from WA https://github.com/ARM-software/workload-automation/pull/1074 

Please could you fetch the latest version and see if this resolves your issue?

**Comment by dlezcano** [comment]
Hi, I have tried the fix, now I have this:

INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing run
WARNING  Depreciated parameter supplied for "telnet" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "password_prompt" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "original_prompt" in "generic_linux". The value will be ignored.
INFO     Initializing execution context
INFO     Connecting to target
ERROR    Exception: key cannot be used for signing
ERROR    Traceback (most recent call last):
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2109, in run
ERROR        handler(self.auth_handler, m)
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
ERROR        sig = self.private_key.sign_ssh_data(blob)
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/agent.py", line 418, in sign_ssh_data
ERROR        raise SSHException("key cannot be used for signing")
ERROR    paramiko.ssh_exception.SSHException: key cannot be used for signing
ERROR    
ERROR    SSH logic error: No existing session
INFO     Done.
INFO     Run duration: N/A
INFO     Ran a total of 0 iterations: 
INFO     Results can be found in /var/www/wa_output/Linux/schbench
WARNING  There were errors during execution.
WARNING  Please see /var/www/wa_output/Linux/schbench/run.log

**Comment by marcbonnici** [comment]
Ok, it looks like it is still looking for SSH keys even if you're using a password and it's finding a non suitable key. Could you either rename your .ssh directory so it doesn't find any keys or generate a new pair that can be successfully detected even if they're not used to see if that is the issue?

**Comment by dlezcano** [comment]
If renamed on the host side:

INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing run
WARNING  Depreciated parameter supplied for "telnet" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "password_prompt" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "original_prompt" in "generic_linux". The value will be ignored.
INFO     Initializing execution context
INFO     Connecting to target
ERROR    SSH logic error: Server '192.168.0.32' not found in known_hosts
INFO     Done.
INFO     Run duration: N/A
INFO     Ran a total of 0 iterations: 
INFO     Results can be found in /var/www/wa_output/Linux/schbench
WARNING  There were errors during execution.
WARNING  Please see /var/www/wa_output/Linux/schbench/run.log

If renamed on the target side:
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing run
WARNING  Depreciated parameter supplied for "telnet" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "password_prompt" in "generic_linux". The value will be ignored.
WARNING  Depreciated parameter supplied for "original_prompt" in "generic_linux". The value will be ignored.
INFO     Initializing execution context
INFO     Connecting to target
ERROR    Exception: key cannot be used for signing
ERROR    Traceback (most recent call last):
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2109, in run
ERROR        handler(self.auth_handler, m)
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/auth_handler.py", line 298, in _parse_service_accept
ERROR        sig = self.private_key.sign_ssh_data(blob)
ERROR      File "/usr/local/lib/python3.6/dist-packages/paramiko/agent.py", line 418, in sign_ssh_data
ERROR        raise SSHException("key cannot be used for signing")
ERROR    paramiko.ssh_exception.SSHException: key cannot be used for signing
ERROR    
ERROR    SSH logic error: No existing session
INFO     Done.
INFO     Run duration: N/A
INFO     Ran a total of 0 iterations: 
INFO     Results can be found in /var/www/wa_output/Linux/schbench
WARNING  There were errors during execution.
WARNING  Please see /var/www/wa_output/Linux/schbench/run.log

**Comment by marcbonnici** [comment]
Yes sorry I meant on the host, so that looks like that was the issue. 
From that message you will also need to add 'strict_host_check=False' to your config if the server is not in your known_hosts.

**Comment by dlezcano** [comment]
I have added the option in my .ssh config
StrictHostKeyChecking no

But I still have the error.

Shouldn't be the ssh connection to pass the option on the invokation with the -o option ? Like
ssh -o StrictHostKeyChecking=no

**Comment by marcbonnici** [comment]
Sorry that was a WA configuration parameter. Can you try adding that to you device_config? That is then passed when initialising the connection.

**Comment by dlezcano** [comment]
I've added the parameter to my barod config file in the device_config section as follow:
device_config:
    host: '192.168.0.32'
    username: 'root'
    password: 'root'
    strict_host_check: False

But I still have the issue

**Comment by marcbonnici** [comment]
You still have the
"ERROR SSH logic error: Server '192.168.0.32' not found in known_hosts" error displayed? Could you send me your run.log for that run to see what might be causing that. 

Also could you try manually connecting to the board so it is in your known hosts and then try it again?

**Comment by dlezcano** [comment]
[run.log](https://github.com/ARM-software/workload-automation/files/4307912/run.log)

Manual connection is find but still have the issue

**Comment by marcbonnici** [comment]
That seems to indicate the original "key cannot be used for signing"  can you move your .ssh folder on the host and still include the strict_host_check parameter?

**Comment by dlezcano** [comment]
Done but without success.

**Comment by dlezcano** [comment]
Based on the issue here:
  https://github.com/paramiko/paramiko/issues/1574
I was able to run the test but I don't know if it is the right fix and it is actually related to devlib.
diff --git a/devlib/utils/ssh.py b/devlib/utils/ssh.py
index b871e22..dcb76f7 100644
--- a/devlib/utils/ssh.py
+++ b/devlib/utils/ssh.py
@@ -362,6 +362,8 @@ class SshConnection(SshConnectionBase):
                 password=self.password,
                 key_filename=self.keyfile,
                 timeout=self.timeout,
+                look_for_keys=False,
+                allow_agent=False
             )
 
             return client

**Comment by marcbonnici** [comment]
Thanks for the link, yes that looks like a correct fix for the SSH key problem so shall  need to submit a fix set these parameters appropriately, however I would not have expected it to fix the unknown_host issue.
Although with that modification your setup is now fully  working?

**Comment by dlezcano** [comment]
Yes it is fully working

**Comment by marcbonnici** [comment]
I've submitted a PR to devlib (https://github.com/ARM-software/devlib/pull/473) to disable the check for SSH keys when using a password, could you pull that an check your system still works?

**Comment by marcbonnici** [comment]
Assuming this has been fixed, please reopen if this is not the case.
