### ISSUE TITLE
Dockerfile revision needs updating

### ISSUE THREAD

**Issue by jimboatarm** [ARM-software/workload-automation#1155]
**Describe the issue**
/workload-automation/extras/DockerFile refers to 19.10 which leads to various EOL error messages (see below).  As the Docker file is aimed at working out of box this could be bumped up 20.04 (seems to wfm).
E: The repository 'http://security.ubuntu.com/ubuntu eoan-security Release' does not have a Release file.

**Run Log**
Please attach your `run.log` detailing the issue.  

**Other comments (optional)**

**Comment by marcbonnici** [comment]
Thanks for pointing this out. This should be fixed with https://github.com/ARM-software/workload-automation/pull/1156.
Please let me know if you encounter any other issues.
