### ISSUE TITLE
Add support for PC Mark for Android

### ISSUE THREAD

**Issue by punitagrawal** [ARM-software/workload-automation#117]
It would be great to have PC Mark for Android[0] support in WA. 

The benchmark needs a button click to start after launching and shows the results at the end. As such it maybe a good candidate for the UI automation WA uses.

[0] https://www.futuremark.com/benchmarks/pcmark-android

**Comment by setrofim** [comment]
Had a brief look at the PC Mark. It looks like the entire benchmark is implemented in side a WebView, which will make device-agnostic instrumentation difficult.

**Comment by jimboatarm** [comment]
I had a look and I think we can do something despite the webView.  I will look at this next week and let you know.

**Comment by setrofim** [comment]
PC Mark has been added (at some point -- this is very very old...)
