### ISSUE TITLE
can we configure an agenda to loop indefinitely?

### ISSUE THREAD

**Issue by jneanne** [ARM-software/workload-automation#1185]
I want to perform MTBF (Mid Time Between Failures) Test using WA.
I know how to stop when a failure is met:
bail_on_job_failure : True
I can set a very High iteration number but can I just run an agenda in loop until an error occurs?

Regards.

**Comment by marcbonnici** [comment]
Hello,

No I'm afraid this is not something we have support for. To get close to the behavior you want, as you mentioned you could either set the iteration number to a large value or perhaps you could wrap the `wa` invocation itself in an infinite loop as part of a shell script (exiting on an error condition)? This way you can resuse the same agenda of X iterations and just change the output directory each invocation to track the number of successful jobs?

**Comment by jneanne** [comment]
Wrapping invocation into shell sounds like the best/simple option then since we won't have to deal with all the results of the run that went correctly. 

Thanks.

**Comment by marcbonnici** [comment]
Assuming this is resolved for now. Please feel free to reopen if you have further questions.
