### ISSUE TITLE
WA（ workload automatic）running  issue

### ISSUE THREAD

**Issue by zuozhengkun** [ARM-software/workload-automation#121]
Hello, Leo
  I   downloaded  patch  from :
https://github.com/ARM-software/workload-automation
and  installed   on  my  untun--linux  PC  according to  your  installation.rst .
and  config  the  android  SDK  well, ...
after  setup  Dhrystone2i.apk on  my  phone,   and 
sudo wa run -f  dhrystone

but failed ,  info displayed  as  followings,
SPREADTRUM\zhengkun.zuo@zkzubtpc:/usr$ sudo wa run -f  dhrystone
 > INFO     Removing existing output directory.
 > INFO     Creating output directory.
 > INFO     Initializing
 > INFO     Running workloads
 > INFO     Connecting to device
 > INFO     Initializing device
 > INFO     Initializing workloads
 > INFO     Running workload 1 dhrystone (iteration 1)
 > INFO         Setting up
 > INFO         Skipping the rest of the iterations for this spec.
 > ERROR    Error while running dhrystone:
 > ERROR        <<Workload dhrystone>'s arm64 dhrystone> could not be found
 > INFO     Job status was FAILED. Retrying...
 > INFO     Skipping workload 1 dhrystone (iteration 2)
 > INFO     Finalizing workloads
 > INFO     Finalizing.
 > INFO     Processing overall results
 > INFO     Status available in wa_output/status.txt
 > INFO     Done.
 > INFO     Run duration: 6 seconds
 > INFO     Ran a total of 2 iterations: 1 FAILED, 1 SKIPPED
 > INFO     Results can be found in wa_output
 > WARNING  There were errors during execution.
 > WARNING  Please see wa_output/run.log
------------------------------------------------------------------

and  also  checked  installation.rst   APK Files sections 
> ================ ============================================ ========================= ============ ============
 > workload         package                                      name                      version code version name
 > ================ ============================================ ========================= ============ ============
 > andebench        com.eembc.coremark                           AndEBench                       v1383a         1383
 > angrybirds       com.rovio.angrybirds                         Angry Birds                      2.1.1         2110
 > angrybirds_rio   com.rovio.angrybirdsrio                      Angry Birds                      1.3.2         1320

maybe  the   install   SW  dhrystone apk  or   temple-run  is  Not  correct ?
it  Need   check   them.

Thanks .

**Comment by ep1cman** [comment]
Dhrystone does not use an APK it uses a binary that is stored in:
workload-automation/wlauto/workloads/dhrystone/bin/arm64/dhrystone

The arm64 binary was only recently added so please make sure you have the latest version of WA from github.

**Comment by zuozhengkun** [comment]
oh,
but   /.workload-automation/wlauto/workloads/dhrystone/bin/arm64'  not  found the  bin files,

/.workload_automation  includes files :
/.workload_automation$ ll
 total 92
 drwxr-xr-x 10 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 24 15:09 ./
 drwxr-xr-x 57 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 24 16:13 ../
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 commands/
 -rw-r--r--  1 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users 15415 Mar 24 15:02 configbak.py
 -rw-r--r--  1 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users 15402 Mar 24 15:09 config.py
 -rw-r--r--  1 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users 15402 Mar 24 15:06 config.py~
 -rw-r--r--  1 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users   793 Mar 23 14:46 config.pyc
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 dependencies/
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 devices/
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 instruments/
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 modules/
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 resource_getters/
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 result_processors/
 drwxr-xr-x  2 SPREADTRUM\zhengkun.zuo SPREADTRUM\domain^users  4096 Mar 23 10:48 workloads/


But  the  path  includes:
/usr/local/lib/python2.7$ ll dist-packages/wlauto/workloads
 drwxr-sr-x 66 root staff 4096 Mar 23 10:40 ./
 drwxr-sr-x 15 root staff 4096 Mar 23 10:40 ../
 drwxr-sr-x  2 root staff 4096 Mar 23 10:40 andebench/
 drwxr-sr-x  2 root staff 4096 Mar 23 10:40 androbench/
 drwxr-sr-x  2 root staff 4096 Mar 23 10:40 angrybirds/
 drwxr-sr-x  2 root staff 4096 Mar 23 10:40 angrybirds_rio/
 drwxr-sr-x  2 root staff 4096 Mar 23 10:40 anomaly2/
 drwxr-sr-x  2 root staff 4096 Mar 23 10:40 antutu/
 drwxr-sr-x  2 root staff 4096 Mar 23 10:40 apklaunch/

It  must  have  arm64  bin  ?
or  the  bin file  path  is  incorrect .

Thx.

**Comment by zuozhengkun** [comment]
I  directly download  workload-automation.ZIP   from the https://github.com/ARM-software/workload-automation,
Why  it  not  contain  the  arm64  bin files?

**Comment by zuozhengkun** [comment]
drwxr-sr-x 2 root staff 4096 Mar 23 10:40 andebench/
 drwxr-sr-x 2 root staff 4096 Mar 23 10:40 androbench/
 drwxr-sr-x 2 root staff 4096 Mar 23 10:40 angrybirds/
 drwxr-sr-x 2 root staff 4096 Mar 23 10:40 angrybirds_rio/
 drwxr-sr-x 2 root staff 4096 Mar 23 10:40 anomaly2/
 drwxr-sr-x 2 root staff 4096 Mar 23 10:40 antutu/
 drwxr-sr-x 2 root staff 4096 Mar 23 10:40 apklaunch/

These  folders  are  empty  except  that  *.py  files.

**Comment by ep1cman** [comment]
I just downloaded the zip from the github page and I did find the dhrystone binary in the path I listed above. Please check the zip file definitely has this file or use git to clone this repository. 

As for the missing APK files, for legal reasons ARM is not able to distribute these, you will have to source these yourself. Please make sure you get the correct versions.

**Comment by zuozhengkun** [comment]
Hello,
  As for  my operation,  extract this zip, and 
         python setup.py sdist
        sudo pip install dist/wlauto-*.tar.gz
(It is  not  the  top directory ,  relate to  step ?  --->  ~/Documents/EAS/  )

displayed as:
SPREADTRUM\zhengkun.zuo@zkzubtpc:~/Documents/EAS/workload-automation-master$ find -name  dhrystone
./wlauto/workloads/dhrystone
./wlauto/workloads/dhrystone/bin/arm64/dhrystone
./wlauto/workloads/dhrystone/bin/armeabi/dhrystone
./dist/wlauto-2.4.0/wlauto/workloads/dhrystone

##workload-automation-master    surely  includes  : dhrystone/bin/arm64/dhrystone , 

But  the path:  SPREADTRUM\zhengkun.zuo@zkzubtpc:~/.workload_automation$ 
has not the DIR:  wlauto/workloads/dhrystone/bin, even  DIR  wlauto, ...
 it  need  to  mkdir  and  copy  the  bin files  by  manual.  

Thx.

**Comment by zuozhengkun** [comment]
Hello,
  Through  opertion,
SPREADTRUM\zhengkun.zuo@zkzubtpc:~/Documents/EAS/workload-automation-master$ sudo cp  wlauto/workloads/dhrystone/bin/arm64/dhrystone  /usr/local/lib/python2.7/dist-packages/wlauto/workloads/dhrystone/bin/arm64
--->resovled.
it  runs well,  it  sees that  the  DIR  ~/.workload_automation   Not   available.

But  I  still want  to  modify  some config, e.g.: 
execution_time, 'cci_pmu_logger', trace-cmd ...
to check  and config  this  file:  :~/.workload_automation/config.py , but  tested and  failed, not  effect.

So  how  can  i   check and  config  the above  files  by  my requirements.
Plz  list  those  files  and   the  existed  PATH . (Or detailed guides doc ..)

Thanks  very much.

**Comment by zuozhengkun** [comment]
and  how to  use  and  run   thses cases:
local/lib/python2.7/dist-packages/wlauto/workloads/rt_app/use_cases/use_cases
├── browser-long.json
├── browser-short.json

**Comment by zuozhengkun** [comment]
sudo wa  run  -f  templerun
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
CRITICAL <<Workload templerun>'s revent> could not be found

In  addition,  revent  file:
The files must be called ``<device name>.(setup|run).revent``, where
``<device name>`` is the name of your device (as defined by the ``name``
attribute of your device's class). WA will look for these files in two
places: ``<install dir>/wlauto/workloads/<workload name>/revent_files``
and ``~/.workload_automation/dependencies/<workload name>``. 

I cp  these files to  the above DIR, but  how can i  get   <device name>`` is the name of your device (as defined by the ``name`` attribute of your device's class).
=====>how  to find it, where  is   the files  and  sections.

thanks.

**Comment by zuozhengkun** [comment]
CRITICAL <<Workload templerun>'s revent> could not be found

**Comment by zuozhengkun** [comment]
CRITICAL <<Workload templerun>'s revent> could not be found

**Comment by zuozhengkun** [comment]
CRITICAL   <Workload templerun>'s revent   could not be found

**Comment by zuozhengkun** [comment]
revent_files
│   ├── Nexus10.run.revent
│   └── Nexus10.setup.revent

**Comment by zuozhengkun** [comment]
Hello,
  Have  you  any   update  for  the   revent_files  process,    that  is  the  files:
  Nexus10.run.revent,  Nexus10.setup.revent ,  what  is  the  keyword  'Nexus10'  dependened on ?
How are they relate to  them... (Named and  usage etc).

Thx.

**Comment by zuozhengkun** [comment]
sudo wa   run -f   templerun
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload 1 templerun (iteration 1)
INFO     	Setting up
INFO     	Skipping the rest of the iterations for this spec.
ERROR    Error while running templerun:
ERROR    	<no-one's arm64 revent> could not be found
INFO     Job status was FAILED. Retrying...

**Comment by zuozhengkun** [comment]
sudo wa   run -f   templerun
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload 1 templerun (iteration 1)
INFO     	Setting up
INFO     	Skipping the rest of the iterations for this spec.
ERROR    Error while running templerun:
ERROR    	<no-one's arm64 revent> could not be found
INFO     Job status was FAILED. Retrying...

**Comment by zuozhengkun** [comment]
<no-one's arm64 revent> could not be found

**Comment by zuozhengkun** [comment]
no-one's arm64 revent could not be found

**Comment by zuozhengkun** [comment]
no-one's arm64 revent could not be found

**Comment by zuozhengkun** [comment]
OK.
Many files  are   in  short  of  in some folders.  ..

This  is   issue  resloved  by  myself.

**Comment by zuozhengkun** [comment]
OK.
Many files  are   in  short  of  in some folders.  ..

This  is   issue  resloved  by  myself.

**Comment by ep1cman** [comment]
Could you tell us your python version and pip version? It seems something is going very wrong when installing WA hence it cannot find the binaries. I would recommend updating to the latest version of pip before trying to install WA with:
`sudo pip install --upgrade pip`

**Comment by ep1cman** [comment]
In regards to the the revent recordings, the device name should match the one you have specified in your  WA run agenda. The most common one is `generic_android`

**Comment by zuozhengkun** [comment]
Yes, 
it  is   named  device   generic_android.

**Comment by zuozhengkun** [comment]
in  config.py ,
device_config = dict(
  # This specifies the device's CPU cores. The order must match how they
    # appear in cpufreq. The example below is for TC2.
    # core_names = ['a7', 'a7', 'a7', 'a15', 'a15']

    # Specifies cluster mapping for the device's cores.
    # core_clusters = [0, 0, 0, 1, 1]

Must the above  items   config  and  match  my  board ?
my  platform  is   big-Little arch, 4  A53, 4 A57. and need  fill them  in the array ?
...

**Comment by zuozhengkun** [comment]
SPREADTRUM\zhengkun.zuo@zkzubtpc:/usr$ sudo wa run -f   antutu
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
CRITICAL <<Workload antutu>'s apk> could not be found

----------
Actually  DIR  has  apk files:
/usr/local/lib/python2.7/dist-packages/wlauto/workloads/antutu$ ll
total 43404
drwxr-sr-x  4 root staff     4096 Mar 30 15:41 ./
drwxr-sr-x 67 root staff     4096 Mar 25 14:10 ../
-rw-r--r--  1 root staff  9400661 Mar 30 15:40 antutu.apk
-rw-r--r--  1 root staff 34997843 Mar 30 13:31 antutu_benchmark_5.3.0.apk
drwxr-sr-x  3 root staff     4096 Mar 30 15:36 bin/
-rw-r--r--  1 root staff     6139 Mar 29 17:15 com.arm.wlauto.uiauto.antutu.jar

Why  not  it  run  well ?

**Comment by ep1cman** [comment]
Leaving `core_names` as its default should not affect the workloads you have currently run but I would recommend setting it to match your device.

The reason WA was not able to find the antutu apk file is because it is looking for version 6.0.1, if you wish to use 5.3.0 you will need to change that in your agenda.

**Comment by ep1cman** [comment]
With the latest commit 12dfbef, the error message about the missing APK file should now be clearer

**Comment by zuozhengkun** [comment]
oh,  OK.

 thanks.

**Comment by zuozhengkun** [comment]
Hello,  
  but  refer to  your  latest commit 12dfbef,  and added ,
  it  run error as  below,
  load_commands(parser.add_subparsers(dest='command'))  # each command will add its own subparser
  File "/usr/local/lib/python2.7/dist-packages/wlauto/core/entry_point.py", line 40, in load_commands
    ext_loader = ExtensionLoader(paths=settings.extension_paths)
  File "/usr/local/lib/python2.7/dist-packages/wlauto/core/extension_loader.py", line 162, in __init__
    self._load_from_packages(self.packages)
  File "/usr/local/lib/python2.7/dist-packages/wlauto/core/extension_loader.py", line 304, in _load_from_packages
    for module in walk_modules(package):
  File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/misc.py", line 138, in walk_modules
    mods.extend(walk_modules(submod_path))
  File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/misc.py", line 133, in walk_modules
    root_mod = __import__(path, {}, {}, [''])
  File "/usr/local/lib/python2.7/dist-packages/wlauto/instrumentation/coreutil/__init__.py", line 29, in <module>
    from wlauto.core.execution import ExecutionContext
  File "/usr/local/lib/python2.7/dist-packages/wlauto/core/execution.py", line 56, in <module>
    from wlauto.core.resolver import ResourceResolver

**Comment by zuozhengkun** [comment]
ERROR    Error while running workload:
ERROR    	INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.antutu.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.antutu.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: UiSelector[CLASS=android.widget.TextView, RESOURCE_ID=com.antutu.ABenchMark:id/start_test_text]
ERROR    	at com.android.uiautomator.core.UiObject.click(UiObject.java:392)
ERROR    	at com.arm.wlauto.uiauto.antutu.UiAutomation.hitTestButtonVersion5(UiAutomation.java:162)
ERROR    	at com.arm.wlauto.uiauto.antutu.UiAutomation.runUiAutomation(UiAutomation.java:68)
ERROR    	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR    	at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR    	at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR    	at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR    	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR    	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:305)
ERROR    
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner

**Comment by zuozhengkun** [comment]
my Dir  included  as  below, 
/usr/local/lib/python2.7/dist-packages/wlauto/workloads/antutu$ ll
total 49892
drwxr-sr-x  2 root staff     4096 Mar 30 18:05 ./
drwxr-sr-x 67 root staff     4096 Mar 25 14:10 ../
-rw-r--r--  1 root staff  9760655 Mar 30 16:47 antutu-benchmark-3-3-2-en-android.apk
-rw-r--r--  1 root staff 34997843 Mar 30 17:16 antutu_benchmark_5.3.0.apk
-rw-r--r--  1 root staff  6284631 Mar 30 17:56 com.antutu.ABenchMark.6.0.1.apk
-rw-r--r--  1 root staff     6139 Mar 30 16:45 com.arm.wlauto.uiauto.antutu.jar

**Comment by zuozhengkun** [comment]
ok, 
I  have  known that the phone  screen  must  be  set  ON !!!

**Comment by zuozhengkun** [comment]
Hello, 
 Another  question,  when the  WA  output  trace.dat,  and  then  how  to   relate to the  trappy  tools,
which  can  use  this  trace.dat.
Can  you  tell me  those  detailed  steps..

Thanks.

**Comment by ep1cman** [comment]
You can tell WA to automatically turn on the devices screen in your agenda/config e.g:

```
device: generic_android
instrumentation: [trace-cmd]
device_config:
    adb_name: 76HBBL5222L7
    enable_screen_check: true
    swipe_to_unlock: vertical
```
As for how to use trappy, you will have to raise a ticket with the trappy team as this is outside of my area of expertise

**Comment by zuozhengkun** [comment]
ok.

thanks.

**Comment by zuozhengkun** [comment]
sudo wa  run -f  ipa_tuning_practical_1_antutu.yaml
Traceback (most recent call last):
  File "/usr/local/bin/wa", line 16, in <module>
    from wlauto.core.entry_point import main
  File "/usr/local/lib/python2.7/dist-packages/wlauto/__init__.py", line 28, in <module>
    from wlauto.common.linux.device import LinuxDevice  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/wlauto/common/linux/device.py", line 32, in <module>
    from wlauto.utils.ssh import SshShell
  File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/ssh.py", line 26, in <module>
    from pexpect import EOF, TIMEOUT, spawn, pxssh
ImportError: cannot import name pxssh

**Comment by zuozhengkun** [comment]
even  run ,
 sudo wa  --version 
also  encounter  the  above   errors?

**Comment by setrofim** [comment]
Please make sure you have pexpect version 3.3 installed.

**Comment by zuozhengkun** [comment]
done:    sudo -H pip uninstall  wlauto 
and then 
sudo -H pip install --upgrade --no-deps wlauto
The  issue  occurs  yet.

**Comment by zuozhengkun** [comment]
I  Have done ,
sudo -H pip install pexpect
        sudo -H pip install pyserial
        sudo -H pip install pyyaml
        sudo -H pip install docutils
        sudo -H pip install python-dateutil
..

**Comment by setrofim** [comment]
version 3.3 is not the latest version of pexpect. Please try

    sudo apt-get remove python-pexpect   # if you had  a previous version installed via apt
    sudo -H pip uninstall pexect
    sudo -H pip install pexpect==3.3

**Comment by zuozhengkun** [comment]
sudo pip install pexpect --upgrade
...
But  failed.

**Comment by zuozhengkun** [comment]
after  apply  your  comments,  OK .

You  are  great!!

**Comment by zuozhengkun** [comment]
sudo    wa run -f  ipa_tuning_practical_1_antutu.yaml

run antutu,  output info,  (config  file,   config.py )
ERROR    Error in insturment trace-cmd
ERROR    trace-cmd returned non-zero exit code 255

 What  does    it  means ?

**Comment by setrofim** [comment]
trace-cmd failed for some reason. Please could you attach the run.log for that run.

**Comment by zuozhengkun** [comment]
Now  it  works well , (Nothing error )
through  modified  these items:
trace_events: ['thermal*']
  trace_buffer_size: 8000
...

**Comment by zuozhengkun** [comment]
Oh, by the way,
 I  remembered   your  said  that :
https://github.com/ARM-software/workload-automation/commit/12dfbef76be6f18a79c2f40ea338c6624deaeacf

I  apply  this  change,  But  it  will  parse  fail...

**Comment by setrofim** [comment]
Please could you clarify what the issue is?

**Comment by zuozhengkun** [comment]
Hello,
Just  now , i  find  the  above  root cause,
because of  trappy installation,  run:
sudo  apt-get install ipython-notebook python-pandas
....

after that, then  i  run  the cmdline: su wa --version
 File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/ssh.py", line 26, in <module>
    from pexpect import EOF, TIMEOUT, spawn, pxssh
ImportError: cannot import name pxssh

It seems that  it  is  conflict  issues  between   WA and  Trappy  tools installations .
How  to  coordinate their  installations.

thanks.

**Comment by zuozhengkun** [comment]
Hello,
Just  now , i  find  the  above  root cause,
because of  trappy installation,  run:
sudo  apt-get install ipython-notebook python-pandas
....

after that, then  i  run  the cmdline: su wa --version
 File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/ssh.py", line 26, in <module>
    from pexpect import EOF, TIMEOUT, spawn, pxssh
ImportError: cannot import name pxssh

It seems that  it  is  conflict  issues  between   WA and  Trappy  tools installations .
How  to  coordinate their  installations.

thanks.

**Comment by setrofim** [comment]
Do not install those packages via apt-get -- install the equivalent packages via pip

(apt has its own dependency steam which force the wrong version of pexpect to be installed)

**Comment by zuozhengkun** [comment]
Oh, yes

**Comment by zuozhengkun** [comment]
And  you  would  help me check  this info ,
 ipython  notebook  BarPlotter.ipynb

Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 9, in <module>
    load_entry_point('ipython==0.13.1', 'console_scripts', 'ipython')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/IPython/frontend/terminal/ipapp.py", line 53, in <module>
    from IPython.utils.path import get_ipython_dir, check_for_old_config
ImportError: cannot import name check_for_old_config

Thank  you very much.

I  raise the ticket  on Trappy  site:
https://github.com/ARM-software/trappy/issues/172
but Not responds  to  us,  (maybe  guess that it belongs to  your teams).


thanks.

**Comment by zuozhengkun** [comment]
or  i got it.
 Need  to  install the  ipython 
sudo pip install ipython==0.13.1
pip install -U ipython

**Comment by zuozhengkun** [comment]
sudo wa --version
/usr/local/lib/python2.7/dist-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/computation/__init__.py:25: UserWarning: The installed version of numexpr 1.4.2 is not supported in pandas and will be not be used
The minimum supported version is 2.1
  "version is 2.1\n".format(ver=ver), UserWarning)
wa 2.4.0

===>pandas ?

**Comment by JaviMerino** [comment]
it's an issue with your installed version of pandas, yes.  Looks like it wants a more recent version of numexpr.  Try this:
```
apt-get remove python-numexpr
pip install numexpr
```

**Comment by zuozhengkun** [comment]
OK;
the above  pass through.
But   prompt,

ValueError: invalid version number '1.1.1rc'

**Comment by zuozhengkun** [comment]
%pylab inline
import trappy
Welcome to pylab, a matplotlib-based Python environment [backend: module://IPython.zmq.pylab.backend_inline].
For more information, type 'help(pylab)'.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-0110ba429caf> in <module>()
      1 get_ipython().magic(u'pylab inline')
----> 2 import trappy

**Comment by ep1cman** [comment]
When you post error messages could you please provide the full traceback/error message along with any logs if they are available.

**Comment by setrofim** [comment]
Also, the latest issue  appears to be with the trappy install, rather than WA? Please could you raise it in the trappy issue trackers, so that its maintainers will see it.

**Comment by zuozhengkun** [comment]
Oh, yes.

Thanks.

**Comment by zuozhengkun** [comment]
Thanks.
