### ISSUE TITLE
Buggy rt-app binary

### ISSUE THREAD

**Issue by douglas-raillard-arm** [ARM-software/workload-automation#1225]
The rt-app binary shipped by WA is ancient (and as a result buggy) as it was never updated since at least 2017.

Now the problem is that recompiling the latest rt-app master is also going to give something buggy (and crashy at the occasion). As a result, LISA ships a patched version, with the following PR branches applied on top of master:
https://github.com/ARM-software/lisa/blob/main/tools/recipes/rt-app.manifest.yaml

These patches are necessary to:
* Run rt-app on android >= 12 (or whatever version in which they relocated tracefs from the typical path)
* Use uclamp

We could update the binaries in WA with the ones compiled in LISA:
https://github.com/ARM-software/lisa/tree/main/lisa/_assets/binaries

Since I've recently added support for ppc64le and x86 (32bits) in `lisa-build-asset`, I could make a build of it for those arch as well.

**Comment by marcbonnici** [comment]
This makes sense and I'm happy to include updated binaries if there are issues with the current (very old) versions.

Just to check I understand the differences in the binaries included in lisa, they are based from the main repo with some additional fixes applied on top? Therefore updating the binairies shouldn't change their existing behaviour, they just adding support for running on additional android versions etc. and some extra features / bug fixes?

**Comment by douglas-raillard-arm** [comment]
Yes that's correct, they are a patched version of the upstream master. I'll build for the missing arch and open a PR
