### ISSUE TITLE
trace-cmd  don't   work  . 

### ISSUE THREAD

**Issue by zuozhengkun** [ARM-software/workload-automation#137]
Hello,
  use  the trace-cmd  tools  instruments  in the same  UT phone,  
1. it  is  always  error in  Antutu case. 
ERROR    Error in insturment trace-cmd
    ERROR    trace-cmd returned non-zero exit code 255
 (to remove more events  in  ftrace event  disabled, but   yet  fails . )

2. But  run Ok  in  dhrystone case. 

 Why?

thanks.

**Comment by setrofim** [comment]
Could you please share your config?

**Comment by zuozhengkun** [comment]
1. enable items:
instrumentation = [
 # Collects traces by interacting with Ftrace Linux kernel internal tracer
    'trace-cmd',
}

###################################### trace-cmd configuration #####################################
# trace-cmd events to be traced. The events can be found by rooting on the device then type
'trace-cmd list -e'
#trace_events = ['power*']

file YAML  :
config:
  device: generic_android
  device_config: 
    logcat_poll_period: 20
#    instrumentation: [cpufreq, trace-cmd, fps, delay]
  instrumentation: [cpufreq, trace-cmd]
#  fps:
#    drop_threshold: 5
#    keep_raw: True
  trace_events: ['thermal*']
#  trace_events: ['all']
#  trace_buffer_size: 30000
# Active cooling (needs the "delay" instrumentation)

=============>
I  Investigated  the issue,  it  is  possible  problems  in the UT  phone  debug  configuration  or  
trace-cmd  version.

Thanks.

**Comment by zuozhengkun** [comment]
1. enable items:
instrumentation = [ # Collects traces by interacting with Ftrace Linux kernel internal tracer 'trace-cmd', }
###################################### trace-cmd configuration #####################################
trace-cmd events to be traced. The events can be found by rooting on the device then type
'trace-cmd list -e'
#trace_events = ['power*']

file YAML :
config:
device: generic_android
device_config:
logcat_poll_period: 20
instrumentation: [cpufreq, trace-cmd, fps, delay]
instrumentation: [cpufreq, trace-cmd]
fps:
drop_threshold: 5
keep_raw: True
trace_events: ['thermal*']
trace_events: ['all']
trace_buffer_size: 30000
Active cooling (needs the "delay" instrumentation)

=============>
I Investigated the issue, it is possible problems in the UT phone debug configuration or
trace-cmd version.

**Comment by ep1cman** [comment]
Is the YAML above the exact configuration you used? WA should (and did when I just tested it) give you a warning about the duplicate entries like `instrumentation`. Could you attach your actual YAML file (you can do this by dragging it into the box where you type these comments)

**Comment by zuozhengkun** [comment]
OK。
Now It  can  work  well,  root cause  in  the  phone configuration.

Thanks.
