### ISSUE TITLE
apk_version instrumentation does not cope with '.' in the version string

### ISSUE THREAD

**Issue by jimboatarm** [ARM-software/workload-automation#139]
Whilst adding this instrumentation to and Adobe Reader workload the following error was produced:

ERROR    Error in insturment apk_version
ERROR      File "/Users/jamhar03/workspace/workload-automation/wlauto/core/instrumentation.py", line 240, in __call__
ERROR        self.callback(context)
ERROR      File "/Users/jamhar03/workspace/workload-automation/wlauto/instrumentation/misc/__init__.py", line 248, in update_result
ERROR        context.result.add_metric(self.name, self.apk_info.version_name)
ERROR      File "/Users/jamhar03/workspace/workload-automation/wlauto/core/result.py", line 268, in add_metric
ERROR        self.metrics.append(Metric(name, value, units, lower_is_better, classifiers))
ERROR      File "/Users/jamhar03/workspace/workload-automation/wlauto/core/result.py", line 314, in __init__
ERROR        self.value = numeric(value)
ERROR      File "/Users/jamhar03/workspace/workload-automation/wlauto/utils/types.py", line 78, in numeric
ERROR        raise ValueError('Not numeric: {}'.format(value))
ERROR    
ERROR    ValueError(Not numeric: 15.3.1)

It doesn't seem to like the '.'

**Comment by setrofim** [comment]
tg

**Comment by ep1cman** [comment]
Should be resolved by: 8d13e1f3414580ca67c437cfa53e186878428409

Instead of using the apk version instrument, versions of Android packages are now automatically attached to the results as "apk_version" classfiers.

**Comment by setrofim** [comment]
Do not use apk_version instrument. It's a bit of a kludge and is now deprecated. With the commit

https://github.com/ARM-software/workload-automation/commit/48259d872bb1eafaf36301e7b2bf41fd57dc4cd7

package version of ApkWorkload will be automatically added as a classifier to the result. To get to appear in your `results.csv`, add either

    csv:
         enable_all_classifiers: true

or

    csv:
         extra_columns: [apk_version]

to your config (the former will make all classifiers added during a run appear as columns in your `results.csv`, the latter will only add "apk_version" column).

**Comment by jimboatarm** [comment]
I've had a quick trial of the changes made.  Here is some feedback.

`enable_all_classifiers` (stated above) should be actually `use_all_classifiers`

The functionality is not as I would have expected.  I expected the returned value to be the version of the APK used during the test.   It appears to return the version for the APK file in the dependencies folder.  So, if there is no host APK the value reported in results.csv will be empty.  If the APK fails to install correctly the host APK version is returned not the version on the device.

I realise this is beyond the issue I reported but can we address these points?

**Comment by setrofim** [comment]
Re-opening to address raised issues

**Comment by setrofim** [comment]
Please could you confirm which benchmark you were running when you have observed that behavior? I have tried running benchmarkpi without an APK present on the host, and I got the installed package's version being reported for that run. Please could you also attach the `run.log` for your run.

>If the APK fails to install correctly the host APK version is returned not the version on the device.

In that case, workload execution should fail with an error. Is this not what you're observing?

**Comment by jimboatarm** [comment]
1) I was using two workloads which we created.  One is a derivative of the applaunch workload, one is custom.  In both cases we saw the following message, even when the APK was in the dependencies folder.

WARNING  Using already installed APK (did not unistall properly?)

Here is a log - [run.log.zip](https://github.com/ARM-software/workload-automation/files/225639/run.log.zip)

Maybe these apps are special in some way. Both used Gmail which is a built it app.

2) I ran ('wa run benchmarkpi') with no APK in dependencies but with it installed on the handset and I got:

CRITICAL <<Workload benchmarkpi>'s apk> (version:None) could not be found

[run.log.zip](https://github.com/ARM-software/workload-automation/files/225654/run.log.zip)

If I add the APK to the dependencies folder it runs ok and I get the version string in results.csv as expected.

**Comment by setrofim** [comment]
For 1)

The log you've sent reports that the version found on target and in the APK are the same, so the version reported in the results is correct.

Regarding the warning (which does not appear in the log you've attached) -- if you're overriding the `teardown()` method, are you remembering to invoke the super's version (I'm assuming you're deriving from `ApkWorkload`)?

**Comment by setrofim** [comment]
For 2)

The run.log.zip you've attached is the same as for 1)

When I run benchmarkpi without an APK I get

     CRITICAL <<Workload benchmarkpi>'s apk> (version:None) could not be found

Which is expected behavior, as by default, WA will expect an APK to be present. You can set `check_apk` workload parameter to `False` to get WA to use the version on target without checking for a local APK.

**Comment by jimboatarm** [comment]
Apologies for the confusing logs.  I get what I need to do now.

However, there is something special about Gmail.  It always generates that warning but at least it runs the test.

**Comment by setrofim** [comment]
Issue resolved by commit 

https://github.com/ARM-software/workload-automation/commit/697aefc7bbe929ecf221d4509eb513703b68ddc1
