### ISSUE TITLE
x86 support for trace-cmd and busybox

### ISSUE THREAD

**Issue by jimboatarm** [ARM-software/workload-automation#154]
This is required to use WA with Intel based Android devices.  Presently WA includes ARM binaries for both of these tools.

**Comment by stevebannister** [comment]
32 & 64 bit variants needed

**Comment by setrofim** [comment]
Done. `busybox` was actually added a while ago. `trace-cmd` added by https://github.com/ARM-software/devlib/commit/e3d9c4b2fdf5b878b51204713c34d7fc6dd6b305

NOTE: even though this is a WA ticket; for WA3, both executables now live inside `devlib` so you need pull the latest version of *that* repo to get this, not the WA repo.

**Comment by setrofim** [comment]
Argh, just noticed @stevebannister's comment. Both are currently  only added as they 64bit versions. I'm assuming (this being 2018 and all) that by this point,  32bit has gone the way of the CRT? If not please re-open.
