### ISSUE TITLE
[Android] Update package name for camera-related workloads

### ISSUE THREAD

**Issue by mdigiorgio** [ARM-software/workload-automation#166]
In Android M and newer version the package name for camera activities has been changed:

* Old package: `com.android.gallery3d`
* New package: `com.android.GoogleCamera`

Also, the button to switch between video and photo mode has been removed and the switch happens by swiping (to the left for video, to the right for taking pictures).

Could you please update this accordingly?

**Comment by ep1cman** [comment]
Should resolved by c0f32237e34d79d987eaf58c59765418d5f374a3
