### ISSUE TITLE
WA automation Feature Requests.

### ISSUE THREAD

**Issue by vinayharitsakp** [ARM-software/workload-automation#173]
WA - Feature Request:

1. Need a Framework where i can have the corresponding config.py file, revents picked for very device Supported.

   Now we run wa as below
     wa run -vf agendas/usecase.yaml

If we can specify the device in the parameter  and the corresponding config files, revents ( if applicable) get picked then it would be easier to maintain once copy of WA and support any number of devices.
   wa run -vf agendas/usecase.yaml S6
   wa run -vf agendas/usecase.yaml mate8

2. If WA can be multi threaded then we will be able to support multiple device runs on a single machine and single copy. If i want to test on 5 devices i need 5 different copies of WA  in 5 different logins for WA to install and get the results.

**Comment by setrofim** [comment]
The first feature is already supported. You can specify an additional config file using `-c` option. A common usage pattern for WA is to create a config file for each device. It may contain the device configuration and any other associated settings (e.g. corresponding daq settings), you can run on a specific device with `wa run -vfc configs/S6.yaml agendas/usecase.yaml`

Handling multiple parallel runs is currently outside the scope of WA. This should be handled by the surrounding infrastructure. This could be a simple shell scripts that wraps WA invocation with multiple config files see: https://github.com/ARM-software/workload-automation/issues/136
