### ISSUE TITLE
python error when running WA tool

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/workload-automation#184]
OS:  64-bit 1604 LTS
Python: 2.7
WA: version 2.5.0

2016-06-21 11:17:07,781 DEBUG    android: adb -s 10.164.4.23:5555 pull '/sdcard/wa-working/screen_capture.png' 'wa_output/idle_big_big_idle_state0_2_1/error.png'
2016-06-21 11:17:09,438 DEBUG    android: adb -s 10.164.4.23:5555 shell "rm '/sdcard/wa-working/screen_capture.png'"
2016-06-21 11:17:09,543 ERROR    Runner: Error while setting up device parameters:
2016-06-21 11:17:09,543 ERROR    Runner: 	Unknown runtime parameter(s): ['ui']
2016-06-21 11:17:09,543 INFO     Runner: 	Skipping the rest of the iterations for this spec.
2016-06-21 11:17:09,544 INFO     Runner: Job status was FAILED. Retrying...
2016-06-21 11:17:09,544 INFO     Runner: Skipping workload big_idle_state0_2 idle_big (iteration 2)
2016-06-21 11:17:09,544 INFO     Runner: Running workload big_idle_state1_1 idle_big (iteration 1)

**Comment by setrofim** [comment]
Please could you share your agenda. It looks like you're specifying "ui"  as a runtime parameter, which does not exist.

**Comment by cloverpop** [comment]
Here is the file:

config:
    device: juno
    device_config:
        bootloader: u-boot
        port: /dev/ttyUSB0
        adb_name: 10.164.4.23:5555
        baudrate: 115200
        modules: [ cgroups, cpuidle ] # device modules required by the instrument
        core_names: [a53, a57, a57, a53, a53, a53]
        core_clusters: [0, 1, 1, 0, 0, 0] # mapping of cores into clusters
    delay:
        fixed_between_iterations: 20
    instrumentation:
    - juno_energy
    - energy_model
    result_processors: []
    energy_model:
        power_scaling_factor: 1000.0
        big_leakage: 120
        idle_workload: idle
        num_of_freqs_to_thermal_adjust: 0
        little_opps:
            450000: 0.850
            800000: 0.900
            950000: 0.950
        idle_workload_params: {}
        power_metric: null
        device_name: null
        big_core: 'a57'
        little_leakage: 60
        no_hotplug: false
        energy_metric: '{core}_cenr'
        big_opps:
            600000: 0.850
            1000000: 0.900
            1200000: 0.950
        first_cluster_idle_state: -1
        performance_metric: 'total number of events'
    cgroups:
        cgroup_root: '/dev/cpuctl'
    idle:
        stop_android: True
sections:
        - id: all
#          boot_params:
#                bootargs : console=ttyAMA0,115200n8 root=/dev/sda2 rw earlyprintk=pl011,0x7ff80000 debug user_debug=31 androidboot.hardware=juno loglevel=9 video=HDMI-A-1:1920x1080R@60
global:
    iterations: 1
workloads:
        - name: sysbench # The workload to be used as load, to compute power when the core is active
          iterations: 3 # the number of times each configuration of the experiment will be repeated to get the data
                        # for energy model generation. If > 1, averages of all iterations will be used and error margins
                        # will be shown in the generated HTML reports
          params:
                test: cpu # the subtest within sysbench to be used
                max_time: 10 # the duration for which a single iteration sysbench workload will run

**Comment by setrofim** [comment]
Fixed by https://github.com/ARM-software/workload-automation/commit/afeb726d534ba8e8bdefd3df2b7c21e94c381401
