### ISSUE TITLE
Need to differentiate Juno r0 /r2 board

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/workload-automation#187]
I found current WA code and Linaro EAS-kernel need to distinguish Juno r0/r2 boards.

Juno r0:  4 A53 + 2 A57
Juno r2:  4 A54 + 2 A72

From WA side, readenergy tool may need to be revised? OPP freq/voltage needs to be revised?
From Kernel side, juno r2 dts needs to be revised and support r0/r2 in parallel.

Thanks.

**Comment by setrofim** [comment]
Core names can be changed via device_config, e.g:

   config:
       device: juno
       device_config:
            core_names: [a53, a72, a72, a53, a53, a53]

I've check the TRM for rev2 and, while ABP register names have changed, their offsets and scaling values have not, so readenergy utility should work with rev2 as-is (I don't have access to a rev2 to confirm). 

Kernel side stuff is nothing to do with WA.
