### ISSUE TITLE
Temperature instrumentation

### ISSUE THREAD

**Issue by jimboatarm** [ARM-software/workload-automation#191]
Could we please have an instrument which polls all of the thermal devices in /sys/devices/virtual/thermal/ every second and dumps them to a csv file?  The sysfs instrument could be extended to provide this functionality.

With this instrument we can make comparative measurements between workloads on the same device.  We could not accurately compare different devices against each other but we could gain useful data.

**Comment by ep1cman** [comment]
There is a file poller instrument that should do exactly that

**Comment by jimboatarm** [comment]
Yay!  Where?

**Comment by jimboatarm** [comment]
Actually we'd like the instrument to be much smarter.  It should go into the directory and discover the list of thermal devices and log them.  Ideally it would get their type too.

**Comment by ep1cman** [comment]
https://github.com/ARM-software/workload-automation/blob/master/wlauto/instrumentation/poller/__init__.py

**Comment by ep1cman** [comment]
Ah i see, I suppose there could be an extended file poller with the logic to do that

**Comment by setrofim** [comment]
This should be a separate instrument,  as the functionality is a lot more specialised -- file_poller should remain generic. Though the new instrument can reuse the same poller binary as the file poller.

**Comment by jimboatarm** [comment]
Just to extend on this topic, I recently used the delay 'instrument' to allow the device to cool between iterations.   The problem faced here is that it is necessary to specify a device specific temperature file in the agenda: 

        temperature_file: '/sys/devices/virtual/thermal/thermal_zone0/temp'

Ideally, the agenda could be kept free from device specific parameters.  So instead can this file become part of the device config?
