### ISSUE TITLE
minior bug: Big cluster Idle_Power graph of report.html is wrong

### ISSUE THREAD

**Issue by cloverpop** [ARM-software/workload-automation#192]
After running WA successfully, report.html file is generated.
In the last "Idle Power" chart for "Big Cluster", it doesn't show "cpu-sleep-0" column.
However, "Idle Power" chart for "Little Cluster" is correct.

**Comment by setrofim** [comment]
I am assuming you're specifically talking about the energy_model instrument? Please could you forward me the (entire) WA output.

**Comment by setrofim** [comment]
Closing as received no response from OP
