### ISSUE TITLE
replay command times out

### ISSUE THREAD

**Issue by setrofim** [ARM-software/workload-automation#198]
The `replay` command `execute()`s `revent` on the target without providing a timeout, which means it times out after the default 30 seconds. 

<h5>Desired behavior:</h5>

Replay command should read the `revent` file (`revent` has `dump` subcommand that can be used for this) and set the timeout based on how long replay actually takes (plus some margin). The same approach can also be used by `ReventWorkload` for setting the default `run` timeout.

**Comment by setrofim** [comment]
It looks like `revent`'s `dump` command is currently broken and needs to be updated to work with the latest format.

**Comment by ep1cman** [comment]
fixed by 259b813a96f632fb9d260689a797f32aadc82c24
