### ISSUE TITLE
Formalizing revent recording format.

### ISSUE THREAD

**Issue by setrofim** [ARM-software/workload-automation#199]
We keep making modifications to revent, as well as widening its use. Some of the modifications affect the binary format of the recording. Currently, this is being done in ad-hock manner; going forward, we should formalize and properly version the binary format. That will allow detecting incompatible recordings and giving meaningful error messages, rather than segfaulting, and development of additional tooling that works with the format.

<h5>proposed additions</h5>

- Add a "magic number" to the beginning of a recording to make easy to identify as such.
- Add a version number to the header of the recording. This will allow revent (and other tools) to detect incompatible recordings.
- The format should be described in WA documentation.

**Comment by ep1cman** [comment]
Implemented by 25eac432c93c90f3b53ff43e5641483ef602309e
