### ISSUE TITLE
[Question] Measure FPS for test case "templerun"

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#205]
Hi there,

If I want to run "temple run" case on Android and want to profiling performance data for its FPS, does WA now support this after I set instrumentation: [fps] in yaml file?

Thanks,
Leo Yan

**Comment by setrofim** [comment]
Yes, that should work.

**Comment by Leo-Yan** [comment]
Thanks @setrofim . Will check this and if have more question will let you know.
