### ISSUE TITLE
Question: timeout for geekbench

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#222]
Hi there,

When run geekbench, it quite often to report timeout issue after geekbench run for about 3 minutes. So I can see the geekbench is still running but WA will report time out like below. I tried to manually to change timeout value in the file workloads/geekbench/**init**.py and wlauto/instrumentation/trace_cmd/**init**.py for big timeout value (300s) but this issue still will happen.

ERROR    Error while running workload:
ERROR       INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    com.arm.wlauto.uiauto.geekbench.UiAutomation:
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.geekbench.UiAutomation
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: 1
ERROR    INSTRUMENTATION_STATUS: numtests=1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Error in runUiAutomation:
ERROR    com.android.uiautomator.core.UiObjectNotFoundException: Did not get to Geekbench results screen.
ERROR       at com.arm.wlauto.uiauto.geekbench.UiAutomation.waitForResultsv3(UiAutomation.java:96)
ERROR       at com.arm.wlauto.uiauto.geekbench.UiAutomation.runUiAutomation(UiAutomation.java:57)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
ERROR    INSTRUMENTATION_STATUS: test=runUiAutomation
ERROR    INSTRUMENTATION_STATUS: class=com.arm.wlauto.uiauto.geekbench.UiAutomation
ERROR    INSTRUMENTATION_STATUS: stack=com.android.uiautomator.core.UiObjectNotFoundException: Did not get to Geekbench results screen.
ERROR       at com.arm.wlauto.uiauto.geekbench.UiAutomation.waitForResultsv3(UiAutomation.java:96)
ERROR       at com.arm.wlauto.uiauto.geekbench.UiAutomation.runUiAutomation(UiAutomation.java:57)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAutomatorTestRunner.java:160)
ERROR       at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutomatorTestRunner.java:96)
ERROR       at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.java:91)
ERROR       at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
ERROR       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
ERROR       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
ERROR  
ERROR    INSTRUMENTATION_STATUS: current=1
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR    INSTRUMENTATION_STATUS: stream=
ERROR    Test results for WatcherResultPrinter=.E
ERROR    Time: 204.376
ERROR  
ERROR    FAILURES!!!
ERROR    Tests run: 1,  Failures: 0,  Errors: 1
ERROR  
ERROR  
ERROR    INSTRUMENTATION_STATUS_CODE: -1
ERROR

**Comment by setrofim** [comment]
Did your adjusted time out values work?, i.e. does it timeout after the amount of time you have specified?

**Comment by ep1cman** [comment]
Did you install WA in development mode? i.e `sudo python setup.py develop` if not then your changes to the code won't take effect untill you run `sudo python setup.py install` again.

**Comment by Leo-Yan** [comment]
Hi @setrofim @ep1cman,

Thanks a lot for the hints. I also changed to use method "sudo python setup.py develop" and finally I found this issue is cased by the timeout set in java file: wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java

So I changed the code as below and the timeout issue can be fixed.

diff --git a/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java b/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java
index 968d2ab..6510c1d 100644
--- a/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java
+++ b/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java
@@ -83,7 +83,7 @@ public class UiAutomation extends BaseUiAutomation {
     public void waitForResultsv2() throws Exception {
         UiSelector selector = new UiSelector();
         UiObject resultsWebview = new UiObject(selector.className("android.webkit.WebView"));
-        if (!resultsWebview.waitForExists(TimeUnit.SECONDS.toMillis(200))) {
+        if (!resultsWebview.waitForExists(TimeUnit.SECONDS.toMillis(500))) {
                 throw new UiObjectNotFoundException("Did not see Geekbench results screen.");
         }
     }
@@ -93,7 +93,7 @@ public class UiAutomation extends BaseUiAutomation {
         UiObject runningTextView = new UiObject(selector.text("Running Benchmarks...")
                                                         .className("android.widget.TextView"));
         runningTextView.waitForExists(TimeUnit.SECONDS.toMillis(2));
-        if (!runningTextView.waitUntilGone(TimeUnit.SECONDS.toMillis(200))) {
+        if (!runningTextView.waitUntilGone(TimeUnit.SECONDS.toMillis(500))) {
                 throw new UiObjectNotFoundException("Did not get to Geekbench results screen.");
         }
     }

WA has many places to set timeout, this sometimes will introduce trouble for long time run case.

**Comment by Leo-Yan** [comment]
Hi @setrofim @ep1cman,

Thanks a lot for the hints. I also changed to use method "sudo python setup.py develop" and finally I found this issue is cased by the timeout set in java file: wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java

So I changed the code as below and the timeout issue can be fixed.

`
diff --git a/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java b/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java
index 968d2ab..6510c1d 100644
--- a/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java
+++ b/wlauto/workloads/geekbench/uiauto/src/com/arm/wlauto/uiauto/UiAutomation.java
@@ -83,7 +83,7 @@ public class UiAutomation extends BaseUiAutomation {
     public void waitForResultsv2() throws Exception {
         UiSelector selector = new UiSelector();
         UiObject resultsWebview = new UiObject(selector.className("android.webkit.WebView"));
-        if (!resultsWebview.waitForExists(TimeUnit.SECONDS.toMillis(200))) {
+        if (!resultsWebview.waitForExists(TimeUnit.SECONDS.toMillis(500))) {
                 throw new UiObjectNotFoundException("Did not see Geekbench results screen.");
         }
     }
@@ -93,7 +93,7 @@ public class UiAutomation extends BaseUiAutomation {
         UiObject runningTextView = new UiObject(selector.text("Running Benchmarks...")
                                                         .className("android.widget.TextView"));
         runningTextView.waitForExists(TimeUnit.SECONDS.toMillis(2));
-        if (!runningTextView.waitUntilGone(TimeUnit.SECONDS.toMillis(200))) {
+        if (!runningTextView.waitUntilGone(TimeUnit.SECONDS.toMillis(500))) {
                 throw new UiObjectNotFoundException("Did not get to Geekbench results screen.");
         }
     }

`

WA has many places to set timeout, this sometimes will introduce trouble for long time run case.

**Comment by setrofim** [comment]
Resolved by https://github.com/ARM-software/workload-automation/commit/088709f2900760a07457bb912734f29805cd208d
