### ISSUE TITLE
Skype: New Update Popup breaks uiautomator

### ISSUE THREAD

**Issue by mcgeagh** [ARM-software/workload-automation#245]
Recently, Skype servers send a signal prompting the app to popup a dialogue asking the user to update the app to the latest version.
This hadnt been witnessed before so the Skype workload does not handle this and gets stuck unable to pass the popup screen and thus fails.

Skype workload should look out for this popup and if detected, dismiss it before continuing.

**Comment by marcbonnici** [comment]
Fixed by https://github.com/ARM-software/workload-automation/commit/cc7684986a828df825a2f13fb44f095729d01e7f
