### ISSUE TITLE
Cannot properly read energy monitor nodes on Juno

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#253]
Hi there,

Now when we want to capture energy data on Juno board, WA doesn't capture energy data from /sys/class/hwmon/hwmon0/, instead WA will directly read registers from /dev/mem by enabling kernel configuration CONFIG_DEVMEM.

So can't WA change to capture energy data from /sys/class/hwmon/hwmon0/? This will be more formal way.

**Comment by setrofim** [comment]
Replace `juno_energy` instrument with `hwmon` in your instrumentation list.
