### ISSUE TITLE
Audio playback issue in bbench on Android 7

### ISSUE THREAD

**Issue by nareshkamboju** [ARM-software/workload-automation#275]
Since default browser not available in Android 7.0.
We have to install known stable version of Chrome or Chromium browser for testing bbench + Audio, Audio and App launch test cases. WA support is need to run chrome or chromium browser on Android 7.0

Please use Linaro releases for testing this activity.
http://releases.linaro.org/android/reference-lcr/hikey/7.0-16.10/

**Comment by setrofim** [comment]
bbench workload is already parametrized to support specifying packages/activities for other browsers.

**Comment by nareshkamboju** [comment]
Finally I just increased size of the /data
partition and this did the trick.

For the WA itself there are 2 news: 1 good and 1 bad
Good news is that we most likely don't need any changes in WA in order
to run bbench+audio workload (still not 100% sure, but checking). I
only updated agenda file and got the browser launched

Bad news is audio can't be played back. I'm getting this exception:
01-11 13:08:56.093   477   492 I ActivityManager: Start proc
2494:com.android.music/u0a38 for service
com.android.music/.MediaPlaybackService
01-11 13:08:56.164  2494  2494 W System  : ClassLoader referenced
unknown path: /system/app/Music/lib/arm64
01-11 13:08:56.204  2494  2494 D AndroidRuntime: Shutting down VM
01-11 13:08:56.205  2494  2494 E AndroidRuntime: FATAL EXCEPTION: main
01-11 13:08:56.205  2494  2494 E AndroidRuntime: Process:
com.android.music, PID: 2494
01-11 13:08:56.205  2494  2494 E AndroidRuntime:
java.lang.RuntimeException: Unable to create service
com.android.music.MediaPlaybackService: java.lang.SecurityException:
MODE_WORLD_READABLE no longer supported
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ActivityThread.handleCreateService(ActivityThread.java:3201)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ActivityThread.-wrap5(ActivityThread.java)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.os.Handler.dispatchMessage(Handler.java:102)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.os.Looper.loop(Looper.java:154)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ActivityThread.main(ActivityThread.java:6119)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
java.lang.reflect.Method.invoke(Native Method)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
01-11 13:08:56.205  2494  2494 E AndroidRuntime: Caused by:
java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ContextImpl.checkMode(ContextImpl.java:2134)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ContextImpl.getSharedPreferences(ContextImpl.java:354)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ContextImpl.getSharedPreferences(ContextImpl.java:349)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
com.android.music.MediaPlaybackService.onCreate(MediaPlaybackService.java:338)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:    at
android.app.ActivityThread.handleCreateService(ActivityThread.java:3191)
01-11 13:08:56.205  2494  2494 E AndroidRuntime:

**Comment by nareshkamboju** [comment]
@setrofim , Have you noticed this problem at your end on Juno board ?

**Comment by setrofim** [comment]
I do not have access to a Juno running Android at the moment, so unable to test. We'll have to look into this when we're adding support for Android 7 (probably going to be some time in Q2). I'll re-open this issue for now.

**Comment by marcbonnici** [comment]
Default browser support has been added with commit https://github.com/ARM-software/devlib/commit/e22d2782673490ec53c11ceb1c1fd450f5f18914.
Renaming issue to better reflect current problem.

**Comment by setrofim** [comment]
Closing with the assumption that the remaining audio issue, was with AOSP on Juno, rather than WA, and that it has since been fixed, or else has become irrelevant.
