### ISSUE TITLE
Warning when trace-cmd instrument is used and ftrace:"false" is in present in rt-app's json file 

### ISSUE THREAD

**Issue by vingu-linaro** [ARM-software/workload-automation#28]
I have a warning if i enable trace-cmd instrument but ftrace:"false" is present if the json file that is run by rt-app:
"trace-cmd instrument cannot be enabled at the same time as ftrace rt-app setting. Please disable trace-cmd instrument in your WA config file or set ftrace to false in the JSON file."

Firstly, ftrace is already set to false in the json file but the value of "ftrace" key is not checked in rt-app config, only the presence is checked
Then, I don't understand why we can't have both trace-cmd instrument and ftrace enabled in json file ? If I want to record some traces with trace-cmd and if i also want that rt-app add it's own trace in the ftrace flow, i have to set ftrace:"true" and to enable trace-cmd

**Comment by setrofim** [comment]
I was under the impression that that was some issue with having the two enabled, but having done some quick test, the two seem to work fine together, so I removed the check: 0b29bda206005f204d685d6333849488a9ce32c5

Thank you for raising this.
