### ISSUE TITLE
Revent replay issues (not finishing, timeout error, empty revent file)

### ISSUE THREAD

**Issue by hosseingolestani** [ARM-software/workload-automation#288]
Hi

I encountered problems working with the WA replay tool. I've installed WA on Ubuntu. My devices is Nexus 4 with Android 4.4.4, and all my tests are done in the latest version of Angry Birds.

*** First problem:
I recorded playing of one stage. When I replay it, the game makes progress up to a point in the middle of the original recorded session, and then stops without any error. (It stops when a bird is pulled back and is not thrown.)
Here's what happened on my command line:
```
me@my_computer:~$ wa replay mako_1.revent 
INFO     Connecting to device...
INFO     Pushing file to device
INFO     Finished replay
```
The same thing happens when I directly replay it from the command line of Nexus:
`root@mako:/ # /data/local/tmp/revent replay /sdcard/wa-working/mako_1.revent`

*** Second problem:
Then I recorded a longer session (playing of two stages). When I replay it, in the middle of the
game (when one stage completes), I receive this error:
```
me@my_computer:~$ wa replay mako_2.revent 
INFO     Connecting to device...
INFO     Pushing file to device
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/core/entry_point.py", line 66, in main
CRITICAL     sys.exit(command.execute(args))
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/commands/record.py", line 94, in execute
CRITICAL     self.run(args)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/commands/record.py", line 158, in run
CRITICAL     self.device.execute(command)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/common/android/device.py", line 447, in execute
CRITICAL     return adb_shell(self.adb_name, command, timeout, check_exit_code, as_root)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/android.py", line 281, in adb_shell
CRITICAL     raw_output, error = check_output(actual_command, timeout, shell=True)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/misc.py", line 129, in check_output
CRITICAL     raise TimeoutError(command, output='\n'.join([output, error]))
CRITICAL 
CRITICAL TimeoutError(Timed out: adb  shell '(/data/local/tmp/revent replay /sdcard/wa-working/mako.revent); echo "
CRITICAL $?"'
CRITICAL OUTPUT:
CRITICAL 
CRITICAL )
```
It seems the connection through adb breaks, and I don't know why.

However, when I directly replay it from the command line of Nexus:
`root@mako:/ # /data/local/tmp/revent replay /sdcard/wa-working/mako_2.revent`
the same thing happens as in the first problem, i.e., the game stops in the middle of the second stage (a bird is pulled back and is not thrown)

*** Third problem
When I record a very short session (just a few touches in the first view of Angry Birds), the generated revent file is absolutely empty (0 bytes).

I'd appreciate it if someone helps me on these issues.

**Comment by marcbonnici** [comment]
The commit bf43bf93bce89bc6f4e132b29d9fbb0797058bea should address these issues.
Would you be able to confirm if this fixes the problems you were having?

**Comment by hosseingolestani** [comment]
I cloned the latest commit from github and installed WA from the source codes. But I'm receiving new errors testing WA on the same device (Nexus 4 with Android 4.4.4).

When I try to record something, this happens:
```
me@my_computer:~$ wa record
INFO     Connecting to device...
CRITICAL Got exit code 969696
CRITICAL from: adb shell "echo 'chmod 0777 /data/local/tmp/wa-bin/disable_screen_lock' | su"
CRITICAL STDOUT: 
CRITICAL STDERR: 
```

When I try to replay a previously recorded version, this happens:
```
me@my_computer:~$ wa replay mako.revent 
INFO     Connecting to device...
INFO     Pushing file to device
INFO     Replaying recording
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/core/entry_point.py", line 66, in main
CRITICAL     sys.exit(command.execute(args))
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/commands/record.py", line 66, in execute
CRITICAL     self.run(args)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/commands/record.py", line 199, in run
CRITICAL     recording = ReventRecording(args.revent)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/revent.py", line 181, in __init__
CRITICAL     self._parse_header_and_devices(self.fh)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/revent.py", line 198, in _parse_header_and_devices
CRITICAL     raise ValueError('{} does not appear to be an revent recording'.format(self.filepath))
CRITICAL 
CRITICAL ValueError(mako.revent does not appear to be an revent recording)

```
Note that I previously installed WA not from the source codes:
`sudo -H pip install wlauto`


Thank you very much.

**Comment by hosseingolestani** [comment]
I cloned the latest commit from github and installed WA from the source codes. But I'm receiving new errors testing WA on the same device (Nexus 4 with Android 4.4.4).

When I try to record something, different kinds of errors happen:
```
me@my_computer:~$ wa record
INFO     Connecting to device...
CRITICAL Got exit code 969696
CRITICAL from: adb shell "echo 'chmod 0777 /data/local/tmp/wa-bin/disable_screen_lock' | su"
CRITICAL STDOUT: 
CRITICAL STDERR: 
```

```
me@my_computer:~$ wa record
INFO     Connecting to device...
CRITICAL Got exit code 969696
CRITICAL from: adb shell "echo 'getenforce' | su"
CRITICAL STDOUT: 
CRITICAL STDERR: error: closed
CRITICAL 
```

```
me@my_computer:~$ wa record
INFO     Connecting to device...
CRITICAL Command 'adb  push '/tmp/tmpCJSnKi' '/sdcard/wa-working/disable_screen_lock'' returned non-zero exit status 1
CRITICAL STDOUT: None
CRITICAL STDERR:
```

```
me@my_computer:~$ wa record
INFO     Connecting to device...
INFO     Press Enter when you are ready to record...

CRITICAL Got exit code 127
CRITICAL from: adb shell "echo 'cd /sdcard/wa-working && /data/local/tmp/wa-bin/busybox nohup /data/local/tmp/wa-bin/revent record -s /sdcard/wa-working/mako.revent' | su"
CRITICAL STDOUT: nohup: can't execute '/data/local/tmp/wa-bin/revent': No such file or directory
CRITICAL 
CRITICAL STDERR: 

```

The last error is more common than the others. `/data/local/tmp/wa-bin/revent` already exists. Actually, when I last checked that directory, it contained these files:
```
/data/local/tmp/wa-bin/
                      |____ busybox
                      |____ disable_screen_lock
                      |____ revent
                      |____ sqlite3

```					  

When I try to execute `revent` from the shell of the Android device, I receive the following error:
```
root@mako:/data/local/tmp/wa-bin # ./revent
/system/bin/sh: ./revent: not executable: magic 7F45
```
This seems to be a cross-compilation error.


I also tried to replay a previously recorded session using the new WA. I receive this error:
```
me@my_computer:~$ wa replay mako.revent 
INFO     Connecting to device...
INFO     Pushing file to device
INFO     Replaying recording
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/core/entry_point.py", line 66, in main
CRITICAL     sys.exit(command.execute(args))
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/commands/record.py", line 66, in execute
CRITICAL     self.run(args)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/commands/record.py", line 199, in run
CRITICAL     recording = ReventRecording(args.revent)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/revent.py", line 181, in __init__
CRITICAL     self._parse_header_and_devices(self.fh)
CRITICAL   File "/usr/local/lib/python2.7/dist-packages/wlauto/utils/revent.py", line 198, in _parse_header_and_devices
CRITICAL     raise ValueError('{} does not appear to be an revent recording'.format(self.filepath))
CRITICAL 
CRITICAL ValueError(mako.revent does not appear to be an revent recording)
```

Note that I previously installed WA in this way:
```
sudo -H pip install wlauto
```
(not from the source codes)


Thank you very much.

**Comment by setrofim** [comment]
Please could you manually delete `/data/local/tmp/wa-bin/` and try recording again? 

The last error

       ValueError(mako.revent does not appear to be an revent recording)

is becuase the new revent will not work wit the old files -- you'll need to re-record

**Comment by hosseingolestani** [comment]
I've already tried removing the contents of both `/data/local/tmp/wa-bin/` and `/sdcard/wa-working/` directories. Before I encountered the errors that I've reported in my previous post, I had removed them all.

Regarding the last error, you are right. If I can record a session with the new version of WA and obtain new `*.revent` files, the error must get resolved.

Thanks

**Comment by marcbonnici** [comment]
The new commit 254e9fff384c7f6356ddd2b6e17b50c0d5f0e239 includes the updated binaries for the previous fixes. Would you be able to try with this and see if that resolves the problem?

**Comment by hosseingolestani** [comment]
The problems seem to be resolved.

I recorded playing of two consecutive stages of Angry Birds. WA could replay it successfully.

I also recorded a very short session containing just one tap. The generated revent file was not empty, and WA could replay it correctly.


Thank you very much.
