### ISSUE TITLE
Move class files from the Base class builds instead of copy

### ISSUE THREAD

**Issue by jumana-arm** [ARM-software/workload-automation#326]
Building the base classes from wlauto/external/uiauto/src/com/arm/wlauto/uiauto/
using the build script wlauto/external/uiauto/build.sh generates the .class files in wlauto/external/uiauto/bin/classes/com/arm/wlauto/uiauto and then copies them into wlauto/common/android/.  

Ideally, the files generated have to be moved into the wlauto/common/android/ directory. than leaving copies in the bin directory.

**Comment by marcbonnici** [comment]
Would you be able to provide some more information as to why this is not desired behavior?

**Comment by jumana-arm** [comment]
The issue was both the folders were being tracked by git, which actually was fixed by a .gitignore fix done before. These JIRA tickets were linked, but executed at wrong times. Closing the issue,
