### ISSUE TITLE
instrumentation/daq: wrong energy cauculation

### ISSUE THREAD

**Issue by rogerable** [ARM-software/workload-automation#328]
In [instrumentation/daq/__init__.py, line 269:](https://github.com/ARM-software/workload-automation/blob/master/wlauto/instrumentation/daq/__init__.py#L269)
`                 energy = sum(data[metrics.index('power')]) * (self.sampling_rate / 1000000)
`

Shouldn't the energy be "divided" by the sampling rate (equivalently timed the sampling period)? We ran a 5-minute workload and got following calculation. Apparently the energy field had some problem.

> $ cat wa_hidroid/results.csv
id,workload,iteration,metric,value,units
glx,gbench,1,Frames_0,1026,frames
glx,gbench,1,FPS_0,34,Fps
glx,gbench,1,PMIC_power,1.334,Watts
glx,gbench,1,PMIC_voltage,4.184,Volts
glx,gbench,1,PMIC_energy,40474.55,Joules

**Comment by setrofim** [comment]
Yes, you are correct, it should be a division. I have no idea what I was thinking when I wrote that. Thank you for catching it!

This is fixed by https://github.com/ARM-software/workload-automation/commit/cb48ece77ffb3c1769d107fc3d81ecb5dc557c85
