### ISSUE TITLE
Stale .class files in wlauto/common/android

### ISSUE THREAD

**Issue by jumana-arm** [ARM-software/workload-automation#333]
The .class files in wlauto/common/android come from wlauto/external/uiauto/build results as far as I understand. 

I do notice some .class files in the wlauto/common/android like UxPerfUiAutomation$SurfaceLogger.class, and many more which I think do not exist anymore. I think the build script should first clear all the .class files in the wlauto/common/android before copying the new ones?

**Comment by marcbonnici** [comment]
Stale classes have been removed in commit 2bd77f08336093a091b41cfdf189314d3fb0dcd4. There should be no need for a script alteration as this was a one off and these classes won't be regenerated in future.
