### ISSUE TITLE
Add display information to __meta folder

### ISSUE THREAD

**Issue by mcgeagh** [ARM-software/workload-automation#335]
Add more meta data to the __meta folder, such as display resolution of the device.

On Android, this can be obtained via SurfaceFlinger:

adb shell dumpsys SurfaceFlinger

**Comment by mcgeagh** [comment]
that file is zero bytes for all of my devices :(

**Comment by setrofim** [comment]
What does `dumpsys window` when you run it on your devices?  Do they all happen to be running N?

**Comment by mcgeagh** [comment]
adb shell dumpsys window

returns a lot of text...
window.dumpsys is still a blank file

**Comment by mcgeagh** [comment]
If i manually run the command wa executes:

adb shell "dumpsys window > /sdcard/tmp.txt"
Error dumping service info: (Unknown error -2147483646) window

**Comment by setrofim** [comment]
Should be fixed by commit https://github.com/ARM-software/workload-automation/commit/490dd404ae2e3341d5e0b81f033cbda40f721994
