### ISSUE TITLE
Support for Chrome devices with ART support

### ISSUE THREAD

**Issue by jimboatarm** [ARM-software/workload-automation#336]
Chrome devices now support Android applications via a container.  Practically this presents a few challenges for WA.

It is possible to establish an ADB connection to the Android container in order to run many WA workloads on Chrome devices.   It is not possible, however, to access many system resources from the Android containere to perform instrumentation and manipulate device configurations.  The sysfs 'files' which are usually used to perform these tasks are mirrored within the Android container, but can only written from the CrOS side.

For example, CPU core governor sysfs registers can only be written from within a CrOS shell.

To resolve this WA would need to be able to connect to the CrOS (via SSH) whilst also connecting to the Android container via ADB.

**Comment by setrofim** [comment]
Implemented on next.
