### ISSUE TITLE
Move fix for no spaces in uiautomation parameters into baseclass

### ISSUE THREAD

**Issue by mcgeagh** [ARM-software/workload-automation#337]
There is a known limitation with uiautomation that doesnt allow you to have spaces in your parameters.

Currently every workload that wants to use spaces, in the python side has to replace it with "0space0", and in the java side reverts it back.

More and more workloads are doing this, so it makes sense to move this logic to the appropriate base classes for both the python and java sides.

Known affected workloads:
- googleslides
- videostreaming
- skype
- youtube
- googleplaybooks
- adobereader

Additional behaviour could be added to this.
For example in adobereader, if we want to pass a list of strings, in python we join lists with "0newline0" into one string, and in java we split on it

**Comment by marcbonnici** [comment]
This functionality has been added in commit 9ba30c27dfc168db51c663b72a8a39e74ce616c3. All parameters are now encoded automatically when added and decoded as their correct data type into the parameter bundle passed to workloads. All existing uiautomator workloads have been updated to use the new functionality in commit 8f1206678abd737fa49ab8643446b69c47b2b4ac.
