### ISSUE TITLE
adobereader failes due to a popup dialog

### ISSUE THREAD

**Issue by setrofim** [ARM-software/workload-automation#340]
adobereader fails on a Pixel due to a new dialog popping up. See the attached run log and UI captures for details.
[applaunch-failure-20170202.tar.gz](https://github.com/ARM-software/workload-automation/files/747536/applaunch-failure-20170202.tar.gz)

**Comment by marcbonnici** [comment]
Resolved by commit 7b7eb05e7fea8ed0cc934bac5a261d2eef5ed37e
