### ISSUE TITLE
BaseUiAutomation getInstance deprecated

### ISSUE THREAD

**Issue by mcgeagh** [ARM-software/workload-automation#343]
In BaseUiAutomation.java (external/uiauto) lines: 215 onwards

UiDevice.getInstance().

is deprecated. See: https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#getInstance()

We should change these calls for the preferred method: https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#getInstance(android.app.Instrumentation)

**Comment by setrofim** [comment]
Migration to UiAutomator2 completed with pull request https://github.com/ARM-software/workload-automation/commit/a4e27128e5f5761a9d241ec5df4a956923a9a00b

**Comment by setrofim** [comment]
Re-opening due to comment:
https://github.com/ARM-software/workload-automation/pull/397#issuecomment-307062557

**Comment by marcbonnici** [comment]
Migration bug fixed with pull request 3653e1b507d707a934147fdc63de545b49591f6c
