### ISSUE TITLE
UiAutomator log isn't independently time stamped. 

### ISSUE THREAD

**Issue by scojac01** [ARM-software/workload-automation#345]
I am trying to resolve some timing issues with an implementation of a workload. I believe it may be a UIAutomator problem and I want to get the timestamps of certain UiAutomator operations.

However when investigating run.log to get the data I need the UiAutomator console output all has the same timestamp (to the ms).

Is it possible to record and output the real timestamps or to view the UiAutomator console output at run time?

**Comment by setrofim** [comment]
There is no straight forward way to get accurate timestamps from console output, however you should be able to find equivalent output in logcat output, which is collected during workload execution.
