### ISSUE TITLE
Error in instrument cpufreq with Android N

### ISSUE THREAD

**Issue by jimboatarm** [ARM-software/workload-automation#351]
When running workloads (e.g. lmbench, Geekbench) with Android N devices the following Error message will be generated.

Tested with Huawei Mate 9 and Google Pixel.

WA added for lmbench on MHAL09_4GB-UGM0216C25000202
INFO     Removing existing output directory.
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
INFO     Running workload lmbench-lat_mem_rd-1024_1024 lmbench (iteration 1)
INFO     	Setting up
INFO     	Executing
ERROR    Error in instrument cpufreq
ERROR    Command 'adb -s UGM0216C25000202 pull '/sys/devices/system/cpu' './wa_output/lmbench/MHAL09_4GB-UGM0216C25000202/20170209-115822/lmbench_lmbench-lat_mem_rd-1024_1024_1/before/sys/devices/system'' returned non-zero exit status 1
ERROR    STDOUT: None
ERROR    STDERR:

**Comment by marcbonnici** [comment]
Not an N specific issue, seems to be related to particular devices.

**Comment by marcbonnici** [comment]
Assume no longer relevant.
