### ISSUE TITLE
add a parameters to use the binary of the target instead of wa's one

### ISSUE THREAD

**Issue by vingu-linaro** [ARM-software/workload-automation#36]
I haven't found any way to prevent wa to push its binary on the target and overwrite the one already in the target. It might be interesting to add a parameter to specify if we want to use local binary in priority. The main issue with binaries that are part of wa, is that they are not up to date with latest bench version

**Comment by setrofim** [comment]
Which binaries in particular are you talking about?

In general, if WA binaries are out of date, then they should be updated, rather than ignored. If you have some binaries patched with no-upstreamable changes, you can get WA to pick up you binares over those included in WA codeline by sticking them into

   ~/.workload_automation/dependencies/<extension name>/bin/<abi>/

Where <extension  name> is the name of the extension (i.e. workload, instrument, etc) to which the binaries belong, and <abi> is the ABI on which the binaries will run (generally, either "armeabi" or "arm64").

**Comment by vingu-linaro** [comment]
if we take the example of rt-app, the binary of arm 32bits should be put here ?
~/.workload_automation/dependencies/workloads/bin/armeabi/

because wa doesn't find it. So i probably use the wrong path

**Comment by setrofim** [comment]
Sorry, I wasn't clear. I mean the actual name of the extesions (not it's type), so in this case,

~/.workload_automationn/dependencies/rt-app/bin/armeabi/

**Comment by vingu-linaro** [comment]
I have put the binary at this location
$ ls ~/.workload_automation/dependencies/rt-app/bin/armeabi/
rt-app

but i still have an error
wa run rt-app   
INFO     Creating output directory.
INFO     Initializing
INFO     Running workloads
INFO     Connecting to device
INFO     Initializing device
INFO     Initializing workloads
CRITICAL rt-app is not installed on the device and could not be
CRITICAL                              found in workload resources

I have removed the rt-app binary from the default installation path 
rm /usr/local/lib/python2.7/dist-packages/wlauto/workloads/rt_app/bin/armeabi/rt-app
to be sure that my version of rt-app was used and not the one installed with wa

**Comment by setrofim** [comment]
I've just pushed a fix. Please pull and try with the updated code.

**Comment by vingu-linaro** [comment]
ok, I have just tested your fix and wa is now able to found and use the binary in: ~/.workload_automation/dependencies/rt-app/bin/armeabi/

but once i have run wa run rt-app, rt-app is no more available on my target whereas it was correctly installed before running wa. I have to re-install it after each use of wa. That would be good to let the target is the same state than before running wa. I haven't check if this wrong behavior is only applicable for rt-app or for all workloads and instruments of wa

**Comment by setrofim** [comment]
I've updated rt-app to not uninstall the binary by default.  

Each extension is responsible for deploying and cleaning up its own resources, so there is no globally-enforced behavior regarding this. However, generally, extensions will only try to remove stuff that they have previously deployed.
