### ISSUE TITLE
Make build-tools and aapt optional

### ISSUE THREAD

**Issue by AnthonyARM** [ARM-software/workload-automation#396]
I don't need to run any APKs (Only command line binaries), as a result I don't need to have build-tools / aapt but the initialisation process fails in utils/android.py in `_init_common()` if I don't have `build-tools` in my path, would it please be possible to make these tools optional ? (Or to raise an exception only if the user tries to use them and they're not available)

**Comment by setrofim** [comment]
Are you running into specific issues; or is this just to remove the need to set `ANDROID_HOME`? 

If it's the latter, then I'm tempted to argue that the benefit is too minor and too niche (the vast majority of users running WA on Android will want to run at least some Android apps) justify prioritizing this.

**Comment by AnthonyARM** [comment]
The issue is that I'm only running on Linux devices at the moment and I still need to have `adb` and `aapt` (Maybe I missed some configuration bit to indicate I'm running only on Linux ?)
Anyway I created a dummy `build-tools/25.0.3/aapt`, it's not ideal but it works

**Comment by setrofim** [comment]
Ah sorry I misunderstood. I thought you were running Linux workloads on Android targets. If you're running on Linux, WA should only be checking for SSH. Changing this to a bug. Please could you confirm that you're observing this issue with the latest  `master`?

**Comment by setrofim** [comment]
Have not heard back from reporter and unable to reproduce; assuming issue is resolved.
