### ISSUE TITLE
ssh.py wrongly assumes the tty is a minimum width

### ISSUE THREAD

**Issue by AnthonyARM** [ARM-software/workload-automation#398]
`ssh.py` assumes the tty is a certain width: `_execute_and_wait_for_prompt` tries to match the input command in `self.conn.before` but if the tty width is too small (The default value seems to be 80 columns) then the command will be truncated which will result in the command not being found in the output which will lead to a crash in the method `file_exists` in `common/linux/device.py` because it assumes the output length is always greater than 1.

This happens if you run wlauto from a Jenkins script as I suspect Jenkins doesn't instantiate a full terminal and I assume the ssh connection inherits its size from the parent terminal ?

One way to fix this is to call `stty cols 300` (Or whatever the minimum width needs to be for wlauto to work) every time the connections is established.
The other option is to break down the commands before sending them over.

**Comment by setrofim** [comment]
Yup, we have a fix for this in `devlib` that was needs to be back-ported.

**Comment by setrofim** [comment]
This pull request contains the changes: https://github.com/ARM-software/workload-automation/pull/399. Please could you try it and let me know whether it fixes the problem on your setup.

**Comment by AnthonyARM** [comment]
Just tried the pull request and it does solve the issue for me indeed!

**Comment by setrofim** [comment]
Fixed by commit https://github.com/ARM-software/workload-automation/commit/51db53d979e877d80bfb57498f59bb657754ebb2
