### ISSUE TITLE
Feature request: Add command-line options to enable/disable instrumentation

### ISSUE THREAD

**Issue by lisatn** [ARM-software/workload-automation#4]
Currently, WA users can enable or disable certain instruments (e.g. cpufreq, interrupts, perf, etc.) by modifying agendas and/or config files. However, it would be nice to add a feature where users can disable an instrument temporarily via command-line for a single run, so they can type a command similar to this:

wa run --disable interrupts dhrystone

if it existed. It'd save time from changing files multiple times and be more convenient.

**Comment by setrofim** [comment]
Implemented in 08bfef961ec78508d6d501e385a03e1d7fd34958
