### ISSUE TITLE
cpustate assumes all cores have equal number of idle states: not true for Mate9

### ISSUE THREAD

**Issue by jumana-arm** [ARM-software/workload-automation#416]
CPU state takes the number of idle states from the little cores. In a Huawei Mate9 device, little cores have 3 idle states where as big cores have 4. This fails the script.

**Comment by setrofim** [comment]
Fixed by https://github.com/ARM-software/workload-automation/commit/a2b0705ff0a9f3de642d837f5e9db8b096e96e6e
