### ISSUE TITLE
Does anamoly2 workload works with apk only?

### ISSUE THREAD

**Issue by bathepawan** [ARM-software/workload-automation#42]
I was using anamoly2 workload but realized it needs game cache to be downloaded.

Where do I need to put that cache to make this workload run?

Please help.

**Comment by setrofim** [comment]
Anomaly 2 will download additional assets as an OBB file. You will need to locate the directory containing this file (and possibly other assets) and tar it up into a tarball called `com.elevenbitstudios.anomaly2Benchmark.tar.gz`. This directory would normally be something like `/sdcard/Android/obb/com.elevenbitstudios.anomaly2Benchmark`, though the exact location may vary depending on the device; see here for more information:

http://developer.android.com/google/play/expansion-files.html

Once you have have the tarball, place it under `~/.workload_automation/dependencies/anomaly2/` (creating that directory if necessary) and WA should be able to pick it up.

Please also note that Anomaly 2 will only run on devices with Google Play middleware installed -- it won't run on standard AOSP builds.

**Comment by bathepawan** [comment]
Thanks setrofim. Got your point.

If I have Game cache with me I will have to copy it to ~/.workload_automation/dependencies/anomaly2/ and then WA will not try to download it again, it this understanding correct?

**Comment by setrofim** [comment]
Yes, if you place the obb directory tarball into the dependencies directory, WA will deploy it after installing the APK, but prior to launching the app, so when the app lauches it will continue installtion using the obb deployed by WA, and will not try to donwload it.

**Comment by bathepawan** [comment]
Thanks, got it.

**Comment by bathepawan** [comment]
Closing issue..
