### ISSUE TITLE
Disable Screen Lock failure

### ISSUE THREAD

**Issue by Nitzeb** [ARM-software/workload-automation#435]
Hi, 

I am novice to WA. I was trying to setup & start running the tests.
I get to see below error:
2017-07-11 15:07:51,086 DEBUG    android: adb shell "echo '/data/local/tmp/wa-bin/disable_screen_lock' | su"
2017-07-11 15:07:51,214 CRITICAL root: Got exit code 1
2017-07-11 15:07:51,214 CRITICAL root: from: adb shell "echo '/data/local/tmp/wa-bin/disable_screen_lock' | su"
2017-07-11 15:07:51,214 CRITICAL root: STDOUT: 
2017-07-11 15:07:51,214 CRITICAL root: STDERR: Error: no such table: locksettings
2017-07-11 15:07:51,214 CRITICAL root: 

This failure pretty much gets repeated in all the tests I tried running.

All preconditions mentioned have been followed:
http://pythonhosted.org/wlauto/device_setup.html

OS : Android 7.1.1
Host OS: Ubuntu 16.04 

Thanks,
Nithin

**Comment by setrofim** [comment]
Thank you for reporting this issue. We have checked it out on a device running 7.1.1, however we were unable to reproduce -- for us, the able seems to be present. Please could you try disabling (if it is already disabled, enabling it, and then disabling it again), just in case that prompts the creation of the appropriate table.

If that doesn't help, it is possible to work around the issue by creating an adapter for your device that turns `disable_screen_lock` into a NOP. Please create a .py file with the following:

```
from wlauto import AndroidDevice

class MyDevice(AndroidDevice):
    name = 'mydevice'
     
    def disable_screen_lock(self):
         pass
```

And drop it under `~/.workload_automation/devices/` (creating that directory if it doesn't already exist). Then, update your `~/.workload_automation/config.py` to use your device by updating the appropriate setting: `device = "mydevice"` (or make the equivalent change in your agenda, if you're specifying the device via that).

Please let me know if either of the above resolves your issue.
