### ISSUE TITLE
Instrument extension directory is non-obvious

### ISSUE THREAD

**Issue by yln** [ARM-software/workload-automation#440]
The `wlauto.core.bootstrap._EXTENSION_TYPE_TABLE` specifies the default search path for instrument extensions to be `instruments` (consistent with commands, devices, etc..)
However the wa implementation path/package for standard instruments is `wlauto.instrumentation`, which is an ?unnecessary? diversion from the expected. (I just spent some time wondering why my custom instrument doesn't get picked up.)

In case this is fixed, I would vote for changing the folder name (*instrumentation -> instruments*, even though it's more work and requires source file changes) instead of changing the default path (so nothing changes for people with custom instruments; also: it's more consistent with respect to other folder names).

**Comment by setrofim** [comment]
Renamed in WA3
