### ISSUE TITLE
usage of WA

### ISSUE THREAD

**Issue by Nitzeb** [ARM-software/workload-automation#450]
Hi WA Team,

Should WA be used with debug builds or with User builds?
While using WA with **user builds**, we normally see error messages  related to pulling logs:
 
$ wa run homescreen
INFO     Running workload 1 homescreen (iteration 1)
INFO     	Setting up
INFO     	Executing
ERROR    Error in instrument cpufreq
ERROR    Command 'adb  pull '/sys/devices/system/cpu' 'wa_output/homescreen_1_1/before/sys/devices/system'' returned non-zero exit status 1
ERROR    STDOUT: None
ERROR    STDERR: 

Could you please provide detailed information about how to execute the tests (say, wa run homescreen)

**Comment by setrofim** [comment]
It looks like, adb is failing to pull cpu sysfs nodes in your user builds. If you don't care about those, you can just disable the cpufreq instrument in your config.

**Comment by setrofim** [comment]
Assuming issue is resovled
