### ISSUE TITLE
Error while running Gmail WA test case

### ISSUE THREAD

**Issue by Nitzeb** [ARM-software/workload-automation#451]
Hi WA Team,

Found below error while trying to run gmail tests via WA.
Gmail account was configured before running the test.

INFO     Running workload 1 gmail (iteration 1)
INFO     	Setting up
INFO     	Skipping the rest of the iterations for this spec.
ERROR    Error while running gmail:
ERROR    	<<Workload gmail>'s file uxperf_1600x1200.jpg> could not be found
INFO     Job status was FAILED. Retrying...
INFO     Skipping workload 1 gmail (iteration 2)

PS: It would be nice to have a quick call to discuss the issues we are facing :)
Lets us know  if this is feasible.

Thanks,
Nithin

**Comment by marcbonnici** [comment]
Hi Nitin,

The image file that the gmail workload uses is not included in WA itself, there are a collection of external assets on github at https://github.com/ARM-software/workload-automation-assets

WA can be configured to automatically search the repository by adding the following line to your config.py file:
``remote_assets_url="https://raw.githubusercontent.com/ARM-software/workload-automation-assets/master/dependencies"``

**Comment by setrofim** [comment]
Assuming issue is resolved.
