### ISSUE TITLE
Device name for a revent workload

### ISSUE THREAD

**Issue by yo51** [ARM-software/workload-automation#466]
Hi, I'm trying to run angry birds but it always says _<Workload angrybirds>'s revent> could not be found_
I tried to rename the revent file in a lot of different ways, but it's still not working. Where can I read the name of my device? Thanks

**Comment by setrofim** [comment]
The name should match the name specified for the `device` entry in WA config. If you're not explicitly specifying that, then it is probably `'generic_android'`.

**Comment by yo51** [comment]
Thanks, it worked. I wrote it wrong, I mispelled
