### ISSUE TITLE
No TelnetPxssh in wlauto/utils/ssh.py

### ISSUE THREAD

**Issue by arnoldlu** [ARM-software/workload-automation#474]
Failed to call TelnetPxssh, please help to fix it.
@ep1cman @Sticklyman1936

**Comment by setrofim** [comment]
This should be fixed by https://github.com/ARM-software/workload-automation/commit/a3d042e05445beb585771f05b5f5fecb6ec9f735. Please let me know if this resolves your issue.

**Comment by arnoldlu** [comment]
Thanks @setrofim , it works.
