### ISSUE TITLE
Problem loading extension: no module named nbformat

### ISSUE THREAD

**Issue by yln** [ARM-software/workload-automation#476]
`CRITICAL:root:Problem loading extensions from package wlauto.result_processors: No module named nbformat`
Reverting 6266edad6f379446776a26af928868e92a86381d fixes the issue for me.

**Comment by setrofim** [comment]
This error should be fixed by https://github.com/ARM-software/workload-automation/commit/b312bf317da051b1bcb601d3d185a76652e5f884. Please let me know if this resolved your issue.

**Comment by yln** [comment]
Yes, this fixes the issue for me! :+1:
