### ISSUE TITLE
Error while running appshare

### ISSUE THREAD

**Issue by yo51** [ARM-software/workload-automation#498]
Hello, I'm having some problems running appshare workload. After setting up and checking dependencies for Skype, Gmail, Cooclephotos and Appshare it starts executing but it gives an error.
This is the error:
ERROR    Error while running workload:
ERROR    	Got exit code 157
ERROR    	from: adb shell "uiautomator runtest /sdcard/wa-working/com.arm.wlauto.uiauto.appshare.jar -e workdir \"/sdcard/wa-working\" -e name \"Echo / Sound Test Service\" -e package_name \"None\" -e package \"['com.google.android.apps.photos', 'com.google.android.gm', 'com.skype.raider']\" -e my_pwd \"password\" -e googlephotos_package \"com.google.android.apps.photos\" -e markers_enabled \"False\" -e my_id \"username\" -e gmail_package \"com.google.android.gm\" -e recipient \"wa-devnull@mailinator.com\" -e skype_package \"com.skype.raider\" -c com.arm.wlauto.uiauto.appshare.UiAutomation#runUiAutomation"
ERROR    	STDOUT: Unsupported standalone parameter.
ERROR    	
ERROR    	STDERR: 

I did not modify anything, I just added the .jpg in the folder and changed .apk in .jar

**Comment by marcbonnici** [comment]
Assuming no longer relevant. Please reopen if this is not the case.
