### ISSUE TITLE
Feature request: Filter or display a list workloads supported by device

### ISSUE THREAD

**Issue by lisatn** [ARM-software/workload-automation#5]
There isn't an easy way to tell which workloads will run on Android, Linux, or both.

So far, workloads such as dhrystone, memcpy, cyclictest, and sysbench have standalone binaries that will run on both Linux and Android devices. Otherwise, it's assumed that the rest depend on Android SDK capabilities and have no Linux support. It isn't as obvious until users look further into the wlauto/workload directory.

**Comment by setrofim** [comment]
Implemented by commit e7fae25821aa099733985e35da2cbd5392df6253
