### ISSUE TITLE
Juno: AOSP latest : Workload automation AndEMark benchmark failed to run

### ISSUE THREAD

**Issue by nareshkamboju** [ARM-software/workload-automation#530]
Juno: Android Oreo : Workload automation AndEMark benchmark failed to run
https://bugs.linaro.org/show_bug.cgi?id=3405

**Comment by nareshkamboju** [comment]
@setrofim One of the observations i noticed is
- The timing of click on - Start- button is not perfect as i could see actions performed by Ui Automator on the screen
- Updating number of  threads from default 6 to 1 is happening
- The run waits at - Start- button and timeouts.

When i clicked manually on the start button the run was able to finish.
It is not a problem of Android Oreo.
Could be Ui Automator.

I will pull latest code and will give a try.
Thank  you.

**Comment by nareshkamboju** [comment]
@setrofim Tested manually on Android Oreo with latest Workload automation master.
The manual run of AndEbench works and it is complete to run.

It is the problem with  Automation script which not getting click on start button on time.
Here is the screen record while running Workload automation on Juno running Android Oreo.
AndEbench automation
https://youtu.be/Acvq-ZUIEDg

**Comment by setrofim** [comment]
AndEMark has not been ported to WA3; as we've had no requests for this, assuming that this is no longer relevant. If that is not the case, please re-open as a request to port AndEMark to WA3.
