### ISSUE TITLE
sqlite db presentation

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#592]
Hello WA team,

I'm putting in place workloads and storing them in the place where we can inspect the content through a web browser. At the same time, I'm storing that in the sqlite DB and use the sqlite_web to see the content via my preferred browser. However, the data organization and presentation is not very intuitive and I was wondering if someone already did this kind of setup with a nice and sexy presentation of the WA results?

**Comment by setrofim** [comment]
There is nothing like that at the moment. We tend to use ad-hoc Jupyter notebooks for result processing and visualisation. In WA3, we'll have a more structured way of handling output that would facilitate this sort of thing.

**Comment by dlezcano** [comment]
Is there a description of the DB ? the tables, perhaps the SQL queries etc ... ?

**Comment by setrofim** [comment]
The schema is in the result processor's code: https://github.com/ARM-software/workload-automation/blob/master/wlauto/result_processors/sqlite.py#L31
