### ISSUE TITLE
Workloads lag between WA2 an WA3 ?

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#603]
Hi,

may be it is not the right place to ask these kind of questions. If there is a better place, please let me know.

I was looking at the different workloads and I see there is a difference between the number of workloads and the type of workloads between WA2 and WA3, why is this diverging?

**Comment by marcbonnici** [comment]
Hello,

There are currently less workloads in WA3 simply due to the fact that they have not all been ported yet. We eventually aim to port all, or at least all the still relevant, workloads from WA2 to WA3 however they have been prioritised lower than getting the core framework itself completed.

**Comment by dlezcano** [comment]
What do you mean by the "still relevant" and "ported" ? WA3 will not be back compatible with WA2 ?

**Comment by setrofim** [comment]
"still relevant" means there is still a need to run them. Some older games (e.g. castlemaster) no longer work on the most recent versions of Android, and are no longer available in the Play store; and some (e.g. dex2oat) had very niche applications, and are probably no longer necessary. 

"ported" means just that.  WA3 is a major redesign of the framework (hence the major version bump).

We do plan to port the vast majority of existing workloads eventually. If there are particular workloads you are interested in, please let us know, and we'll try to prioritise their porting.

> WA3 will not be back compatible with WA2 ?

We are striving for (though cannot guarantee) compatibility at configuration level. Most of your existing agendas should continue to work with WA3, or only require very minor modifications.

The internal structure of the framework and the plugin API are going to be completely different. If you are using custom workloads, instruments, etc. that have not been up-streamed, they will require porting to work with WA3. In most cases, this should be fairly straightforward, and we'll include a migration guide in WA3 documentation when it is released.

**Comment by dlezcano** [comment]
Yes, as we are in the process of contributing, it is hard to base our work on a repo which diverges too much from the previous version. So, if you can post-port the workloads to WA3 it would be nice. We have more we will propose in the meantime.

**Comment by setrofim** [comment]
As I've said, please let us know _which_ WA2 workloads that are not yet in WA3 you're most interested in, and will prioritise porting them. Otherwise, we will get to most of them eventually. 

Unfortunately, we cannot commit to porting anything that has not already been up-streamed to WA2, but we will be happy to provide assistance with specific porting issues.

**Comment by dlezcano** [comment]
I will sort out which workload we need in priority for WA3.

So if we want to submit a workload, we should send it against WA2 ?

**Comment by setrofim** [comment]
At this stage, WA2 is pretty much in "maintenance" mode -- we're mostly taking fixes to existing functionality. New features, such as workloads should really be submitted for WA3 -- as I've said, we cannot commit to migrating anything that's hasn't already been up-streamed. But if this is something relatively small and simple, we can make an exception.

If you're still developing something, I strongly suggest switching to WA3.
