### ISSUE TITLE
Add "process" command

### ISSUE THREAD

**Issue by marcbonnici** [ARM-software/workload-automation#610]
Enable output processors to be easily run offline.

**Comment by Rahlubenru** [comment]
I'm new to python but would like to have a go at completing this.

To be clear I have the right idea, this would be a new command to perform the process part of the run command independently and without access to the device. Would the run command also want an optional argument adding to allow it to stop before the processing step?

**Comment by setrofim** [comment]
> I'm new to python but would like to have a go at completing this.

Sure, this should be relatively straight-forward, and is a good first task to tackle.

>  this would be a new command to perform the process part of the run command independently and without access to the device.

Correct.  `OutputProcessor`'s  do not assume assume the presence of a target connection, and instead rely on results and metadata collected by other parts of the framework. So it should be possible to run then "offline", it's the just the case of implementing a command to do that.

In the past, I've needed to run the `csv` processor on existing results so I've written a short script to do 
that:

https://pastebin.com/EcwxPjkQ

The command implementation would be a generalisation of that, so it might serve as a good starting point for your implementation.

I would also recommend skimming through this:

http://mabonnici-wlauto-doc-test.readthedocs.io/en/documentation_a/developer_guide.html

This is currently a work-in-progress and needs polishing in places, but will provide a general overview of how WA framework works.

>  Would the run command also want an optional argument adding to allow it to stop before the processing step?

No, this is not necessary. If processing is not desirable during a run,  one would simply disable the processor in the agenda.

**Comment by Rahlubenru** [comment]
Thank you. I will take a look at what you've provided and go from there then.

**Comment by setrofim** [comment]
Please make sure you're looking at `next` branch, and not `master` as this ticket is for WA version 3. `master` branch contains version 2, which is the "current published" version, but is no longer actively developed and is in maintenance mode.

**Comment by Rahlubenru** [comment]
Thanks, I knew it would be something obvious

**Comment by Rahlubenru** [comment]
#694 I'm not completely sure about the amount of logging and the descriptions but otherwise I think this is what was requested. Please let me know if I've missed anything.

**Comment by marcbonnici** [comment]
Added by PR https://github.com/ARM-software/workload-automation/pull/701
