### ISSUE TITLE
Port Templerun2 from WA2 to WA3

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#620]
We have a python script for WA2 running the templerun2 workload. We would like to port it to WA3, is there any instructions for that ? Below the script.

"""

Temple Run 2
------------

Temple Run 2 is an endless running game, the runner attempts to escape the
temple. This game has a single heavy thread which dominates the performance,
that means if the particular thread is not scheduled to right core with right
capacity the performance would be bad. This kind of single heavy thread with
other light threads is a typical behavior in games.

Temple Run 2 generate the scenes randomly and does not provide demo mode like
Beach Buggy Blitz. However, we can leverage the tutorial mode to produce
repeatable workload. During the tutorial, the 1st 50m is the same, the runner
runs until a cliff, if the player does not performs jump, the runner will fall
into the cliff, then restart from temple. Therefore, we can leverage this
feature to produce repeatable workload.

**`workloads/templerun2/__init__.py`**
We just leverage tutorial mode to generate reproducible workload.

"""

import time
from wlauto import ApkWorkload, Parameter
from wlauto.utils.android import adb_command

class TempleRun2(ApkWorkload):

    name = 'templerun2'
    description = "A racing game with various and repeatable scene"

    package = "com.imangi.templerun2"
    activity = "com.imangi.unityactivity.ImangiUnityProxyActivity"

    parameters = []

    loading_time = 30 # in sec
    def _skip_tutorial(self):
        # wait 'launch_loading_timeout' sec for loading, then enter tutorial
        self.logger.debug('Waiting for the game to load (1st run)...')
        time.sleep(self.loading_time)

        self.device.execute("input keyevent 3", 20)
        time.sleep(5)

        self.device.execute('am force-stop {}'.format(self.package))
        time.sleep(5)
        self.logger.debug('Tutorial is completed...')

    def _execute(self):
        # We start game here, because any operation in run() will be measured.
        self.launch_application()
        self.logger.debug('Waiting for the game to load (normal run)...')
        time.sleep(self.loading_time)
        self.device.execute("input tap 550 1200", 20)
        self.logger.debug('The game starts running.')
        time.sleep(5)

    def setup(self, context):
        super(TempleRun2, self).setup(context)
        # We do a 1st run here and skip the tutorial
        self._skip_tutorial()
        self.kill_background()
        self.device.clear_logcat()
        self._execute()

    # do nothing here, any operation in this method will be measured.
    def run(self, context):
        time.sleep(10)

    def validate(self):
        pass

**Comment by marcbonnici** [comment]
Hi,

We are currently in the process of creating the documentation for WA3 which will include porting instructions however this is not yet complete.

The main things that you will need to be aware of are:
- all the old `wlauto` imports will now need to be from `wa` instead.
- the `package` attribute will need to be changed to a list of strings called `package_names` (this optionally allows for multiple package names)
- the `device` attribute from the workload is now a devlib `target`. Some of the command names remain the same, however there will be differences and the API can be found here: http://devlib.readthedocs.io/en/latest/target.html
- All apk functionality has re-factored into an `APKHandler` object which is available as the `apk` attribute of the workload. This means that that for example `self.launchapplication()` will now become `self.apk.start_activity()`
- The activity from the apk will be automatically discovered so this can be removed.

Therefore the ported workload should look something like this:

```

import time
from wa import ApkWorkload

class TempleRun2(ApkWorkload):

    name = 'templerun2'
    description = "A racing game with various and repeatable scene"

    package_names = ["com.imangi.templerun2"]

    loading_time = 30 # in sec

    def _skip_tutorial(self):
        # wait 'launch_loading_timeout' sec for loading, then enter tutorial
        self.logger.debug('Waiting for the game to load (1st run)...')
        time.sleep(self.loading_time)

        self.target.execute("input keyevent 3", 20)
        time.sleep(5)

        self.target.execute('am force-stop {}'.format(self.package))
        time.sleep(5)
        self.logger.debug('Tutorial is completed...')

    def _execute(self):
        # We start game here, because any operation in run() will be measured.
        self.apk.start_activity()
        self.logger.debug('Waiting for the game to load (normal run)...')
        time.sleep(self.loading_time)
        self.target.execute("input tap 550 1200", 20)
        self.logger.debug('The game starts running.')
        time.sleep(5)

    def setup(self, context):
        super(TempleRun2, self).setup(context)
        # We do a 1st run here and skip the tutorial
        self._skip_tutorial()
        self.target.execute('am kill-all')
        self.target.clear_logcat()
        self._execute()

    # do nothing here, any operation in this method will be measured.
    def run(self, context):
        time.sleep(10)

```


If you have any other questions please let me know.

**Comment by dlezcano** [comment]
Thanks for the answer. Looking forward to read the documentation.
