### ISSUE TITLE
WA3: exoplayer fails with the version

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#622]
Hi,
currently, the specified version for the exoplayer workload is '2.4.0', I'm using 2.5.4 so I have to update the init.py file with the new version. Is it possible to specify a version wildcard or eg. > 2.4.0 ?

**Comment by marcbonnici** [comment]
Hi,
No we do not currently support wildcard versions or greater than a specific version, however WA3 does support loose version matching so for example if you specify `2.5` in the `__init__.py` file then this will match against versions `2.5.2` `2.5.4` etc.

**Comment by dlezcano** [comment]
Does it make sense to have:
versions = ['2.4.2', '2.5']

**Comment by marcbonnici** [comment]
It would make sense to have multiple versions listed yes. 
I have just tested this workload with version 2.6 which also appears to work so have added both of these versions to the supported versions for the workload with commit https://github.com/ARM-software/workload-automation/commit/fbf1bbb1cfbfa09a9bd5fb7553622210b13e16a0

**Comment by dlezcano** [comment]
It fails with a 2.5 version.
I think this is related to:
2018-02-08 16:19:40,532 DEBUG      resolver:     Resource <<Workload exoplayer>'s apk 2.6> not found.

**Comment by marcbonnici** [comment]
In your agenda you will need to specify `version: 2.5` as by default wa will look for the latest supported version now `2.6`.

**Comment by dlezcano** [comment]
I tried but it still fails. I have the following agenda:

workloads:
  - name: exoplayer
    id: audio_workload_task_placement
    classifiers:
       tag: ogg_128kbps_30s
    workload_parameters:
      format: "ogg_128kbps"
      duration: 30

Where shall I add the version tag ?

**Comment by marcbonnici** [comment]
You would add it as a workload parameter. So something like: 
```
- name: exoplayer
  workload_parameters:
      format: "ogg_128kbps"
      duration: 30
      version: 2.5
```

**Comment by dlezcano** [comment]
Ok, it works now. Thank you very much!
