### ISSUE TITLE
WA3: exoplayer fails to run because of 'get_rotating' error

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#623]
Hi,

I trying to run an exoplayer workload but I get the error:

ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 420, in run_next_job
ERROR            self.do_run_job(job, context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 457, in do_run_job
ERROR            job.setup(context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/job.py", line 101, in setup
ERROR            self.workload.setup(context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/workloads/exoplayer/__init__.py", line 167, in setup
ERROR            self._original_orientation = self.target.get_rotation()
ERROR          File "/usr/local/lib/python2.7/dist-packages/devlib/target.py", line 1373, in get_rotation
ERROR            return int(self.execute(cmd).strip())
ERROR    
ERROR        ValueError(invalid literal for int() with base 10: 'null')
INFO         Completing job wk1
ERROR    Job wk1 iteration 1 completed with status FAILED. Max retries exceeded.

However, running the same workload with the commit-id 833c3dd0a00a0a76e8441da994c96beaf97bb768 runs fine.

**Comment by marcbonnici** [comment]
Hi,

This was due to a bug in devlib, this should now be fixed https://github.com/ARM-software/devlib/commit/f3c8ce975ee3980134a5e306af05bda0e1eb0d5c. Could you update to the latest version of devlib and try again?

**Comment by dlezcano** [comment]
Actually it shifted the error to the end of the test.

ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 420, in run_next_job
ERROR            self.do_run_job(job, context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 488, in do_run_job
ERROR            job.teardown(context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/job.py", line 124, in teardown
ERROR            self.workload.teardown(context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/workloads/exoplayer/__init__.py", line 217, in teardown
ERROR            self.target.set_rotation(self._original_orientation)
ERROR          File "/usr/local/lib/python2.7/dist-packages/devlib/target.py", line 1381, in set_rotation
ERROR            raise ValueError('Rotation value must be between 0 and 3')
ERROR        
ERROR        ValueError(Rotation value must be between 0 and 3)
INFO         Completing job video_workload_task_placement
ERROR    Job video_workload_task_placement iteration 1 completed with status FAILED. Max retries exceeded.

**Comment by marcbonnici** [comment]
Ok, this should now be fixed with commit https://github.com/ARM-software/workload-automation/commit/ff5e5821d05da32020448094c275cfebd0e0346c.

**Comment by dlezcano** [comment]
Yes, confirmed.
