### ISSUE TITLE
WA3: exoplayer audio downloads the ogg file each time

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#624]
Hello dear WA team.

we created a workload with an audio exoplayer:

workloads:
  - name: exoplayer
    classifiers:
       tag: ogg_128kbps_30s
    workload_parameters:
      format: "ogg_128kbps"
      duration: 30

Every workload run downloads http://upload.wikimedia.org/wikipedia/commons/c/ca/Tchaikovsky_-_Romeo_and_Juliet_Ouverture_-_Antal_Dorati_(1959).ogg

If the file is already present, it is pointless to download it again, no ?

**Comment by marcbonnici** [comment]
Hello,

Yes you are correct the workload should only download the file for the first run and then reuse the same file after that.

I have tried to recreate the issue however it seems to run correctly for me. Would you be able to share your run.log?

**Comment by marcbonnici** [comment]
I have managed to recreate this now, yes this is a bug in the workload for that option.

**Comment by dlezcano** [comment]
Oh, I forgot to mention that happens at commit 833c3dd
I can't run the workload using the HEAD because of the get_rotating() issue.

**Comment by marcbonnici** [comment]
Hi, 
This should be fixed with commit https://github.com/ARM-software/workload-automation/commit/5f1145a41fda0fda66c4660d2e354c49ee6b84c7.

Could you update to the latest version of WA and see if these issues are fixed?

**Comment by dlezcano** [comment]
Yes, it is fixed. Thanks!
