### ISSUE TITLE
How to setup an agenda with different configs ?

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#633]
Hi,

I would like to run the same workload but with different configs:
 - different traces (sched metrics, idle metrics)
 - temperature reading
 - prefer-idle, boost
 ...
I know I can invoke "wa run -c myconfig" where the documentation says it can be used as an additionnal configuration file.

 - Is possible to specify different configuration files ? so I can create combinations of different simple config files (example below)

 - I tried with a single config file but it fails with an error: 
  ERROR    Error in "../configs/sched-metrics.yaml":
  ERROR    configuration provided for unknown plugin "global"

Then I removed the global entry and got:
   ERROR           Invalid entry(ies) in "audio_workload_task_placement": "trace-cmd, trace_events"

--------------------------------------------------------

# config file config-sched-metrics.yaml

trace-cmd:
  buffer_size: 120000
trace_events: ['sched_switch',
               'sched_wakeup',
               'sched_wakeup_new',
               'sched_load_avg_cpu',
               'sched_load_avg_task',
               'cpu_capacity',
               'cpu_frequency',
               'cpu_idle',
               'sched_boost_cpu',
               'sched_boost_task',
               'sched_energy_diff',
               'ipi*',
               'sched_find_best_target',
               'sched_group_energy',
               'sched_energy_calc_duration',
               'workqueue*',
               'sched_sugov_util']

# config file disable prefer-idle

runtime_params:
  sysfile_values:
    /dev/stune/top-app/schedtune.prefer_idle: 0
    /dev/stune/foreground/schedtune.prefer_idle: 0

**Comment by setrofim** [comment]
Hm, sounds like it could be a bug.  With WA3, it *should* be possible to specify multiple configs. It looks like the formatting is screwed up. Please could you attach the config files, as well as the agenda, you're using.

**Comment by dlezcano** [comment]
[agenda-configs.tar.gz](https://github.com/ARM-software/workload-automation/files/1715986/agenda-configs.tar.gz)

**Comment by dlezcano** [comment]
IIUC, I can do something similar with the sections, right ?

**Comment by setrofim** [comment]
You don't need the top-level `global:` in either config file; apart from that, they look fine.  I have tried running

`wa run -c ./prefer-idle-disabled.yaml -c ./sched-metrics.yaml exoplayer-audio-test.yaml -v`

(after  removing the `global:`'s) and everything  seems to have parsed correctly.

> IIUC, I can do something similar with the sections, right ?

For runtime parameters, sure. However, it's currently not possible to reconfigure instruments for individual jobs. So things like trace-cmd events can only be specified for the entire run (you *can* enable and disable instruments for specific jobs, however). If you want to collected different sets of events for a set of workloads; doing multiple runs while passing different configs is the way to go at the moment. Support for re-configuring instruments on per-job basis is something we're hoping to add in the near future.

**Comment by dlezcano** [comment]
Ok, I don't know what I did wrong at the first time. I retry and it worked. Sorry for the noise, thanks for double checking that.
I think mixing different configs and different sections is fine for I want to achieve.
