### ISSUE TITLE
rt-app fails at the end of run

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#641]
I'm trying to run the following workload. After the workload finishes it fails with:

INFO     Creating output directory.
INFO     Initializing run
INFO     Connecting to target
INFO     Setting up target
INFO     Initializing execution context
INFO     Generating jobs
INFO         Loading job wk1
INFO     Installing instruments
INFO     Installing output processors
INFO     Starting run
INFO     Initializing run
INFO         Initializing job wk1 [1]
WARNING  Event [sched_energy_diff] not available for tracing
WARNING  Event [sched_group_energy] not available for tracing
WARNING  Event [sched_energy_calc_duration] not available for tracing
WARNING  Event [sched_sugov_util] not available for tracing
INFO     Running job wk1
INFO         Configuring augmentations
INFO         Configuring target for job wk1 [1]
INFO         Setting up job wk1 [1]
INFO         Running job wk1 [1]
INFO         Processing output for job wk1 [1]
INFO         Tearing down job wk1 [1]
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 420, in run_next_job
ERROR            self.do_run_job(job, context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 473, in do_run_job
ERROR            job.process_output(context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/framework/job.py", line 119, in process_output
ERROR            self.workload.update_output(context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/workloads/rt_app/__init__.py", line 180, in update_output
ERROR            self._pull_rt_app_logs(context)
ERROR          File "/usr/local/lib/python2.7/dist-packages/wa/workloads/rt_app/__init__.py", line 277, in _pull_rt_app_logs
ERROR            self.target.pull_file(target_path, host_path, timeout=120)
ERROR    
ERROR        AttributeError('AndroidTarget' object has no attribute 'pull_file')
INFO         Completing job wk1
ERROR    Job wk1 iteration 1 completed with status FAILED. Max retries exceeded.
INFO     Finalizing run
INFO         Processing using "csv"
INFO         Finalizing job wk1 [1]
INFO     Done.
INFO     Run duration: 46 seconds
INFO     Ran a total of 1 iterations: 1 FAILED
INFO     Results can be found in /var/www/wa_output//ASB-2017-11-06_4.9-o-release-2967-g770961336703/camera
WARNING  There were errors during execution.
WARNING  Please see /var/www/wa_output//ASB-2017-11-06_4.9-o-release-2967-g770961336703/camera/run.log

Attached run.log, config file and agenda
[run.log](https://github.com/ARM-software/workload-automation/files/1723779/run.log)
[camera.tar.gz](https://github.com/ARM-software/workload-automation/files/1723784/camera.tar.gz)

**Comment by setrofim** [comment]
Should be fixed by https://github.com/ARM-software/workload-automation/pull/642
