### ISSUE TITLE
Workload rt_app is broken in WA 3.0

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#747]
Hi, there

I found the workload rt-app is broken in WA 3.0, with below code change the testing case can run successfully at my side; I'm not confidence for the change to remove methods ' context.result.classifiers.update', so please check if it's doable for you?

```
diff --git a/wa/workloads/rt_app/__init__.py b/wa/workloads/rt_app/__init__.py
index c3a7313..21540cc 100644
--- a/wa/workloads/rt_app/__init__.py
+++ b/wa/workloads/rt_app/__init__.py
@@ -178,10 +178,10 @@ class RtApp(Workload):
 
     def update_output(self, context):
         self._pull_rt_app_logs(context)
-        context.result.classifiers.update(dict(
-            duration=self.duration,
-            task_count=self.task_count,
-        ))
+        #context.result.classifiers.update(dict(
+        #    duration=self.duration,
+        #    task_count=self.task_count,
+        #))
 
         outfile = os.path.join(context.output_directory, RAW_OUTPUT_FILENAME)
         with open(outfile, 'w') as wfh:
@@ -195,8 +195,8 @@ class RtApp(Workload):
                 pload_value = match.group(1)
                 pload_unit = match.group(2)
                 calib_cpu_value = match.group(3)
-                context.result.add_metric('pLoad', float(pload_value), pload_unit)
-                context.result.add_metric('calib_cpu', float(calib_cpu_value))
+                context.add_metric('pLoad', float(pload_value), pload_unit)
+                context.add_metric('calib_cpu', float(calib_cpu_value))
 
             error_match = ERROR_REGEX.search(line)
             if error_match:
@@ -206,8 +206,9 @@ class RtApp(Workload):
             if crit_match:
                 crit_count += 1
 
-        context.result.add_metric('error_count', error_count, 'count')
-        context.result.add_metric('crit_count', crit_count, 'count')
+        context.add_metric('error_count', error_count, 'count')
+        context.add_metric('crit_count', crit_count, 'count')
+       return
 
     def finalize(self, context):
         if self.uninstall_on_exit:
@@ -274,7 +275,7 @@ class RtApp(Workload):
         self.target.execute(tar_command, timeout=300)
         target_path = self.target.path.join(self.target_working_directory, TARBALL_FILENAME)
         host_path = os.path.join(context.output_directory, TARBALL_FILENAME)
-        self.target.pull_file(target_path, host_path, timeout=120)
+        self.target.pull(target_path, host_path, timeout=120)
         with tarfile.open(host_path, 'r:gz') as tf:
             tf.extractall(context.output_directory)
         os.remove(host_path)
```

**Comment by marcbonnici** [comment]
Hello,

The changes you've made here look similar to some fixes we submitted a little while ago (a52187a114c6a67734462e9a35d27a2116fde487 and https://github.com/ARM-software/workload-automation/pull/642), would you be able to pull the latest version of WA3 and see if these issues are resolved?

**Comment by Leo-Yan** [comment]
Hi @marcbonnici,

I use latest devlib + lastest WA with next branch, finally I get below reports:

leoy@leoy-ThinkPad-X240s:~/Work2/Develop/wa-data$ wa run -c config.yaml -f rtapp_mp3.yaml -d test
ERROR    instrument "trace-cmd" already exists.

**Comment by setrofim** [comment]
This is due to https://github.com/ARM-software/workload-automation/commit/e5ed64d8d5f247eaf3374daf9e1c975b1c61c519. You probably still have a stray `.pyc` file with the old name. Depending on your installation method, it would likely be under `/usr/local/lib/python2.7/dist-packages/wa/instruments/trace-cmd.pyc` or in the analogous location in your source. Please delete the `.pyc` file to resolve the issue.

**Comment by Leo-Yan** [comment]
On Mon, May 14, 2018 at 12:35:48AM -0700, setrofim wrote:
> This is due to https://github.com/ARM-software/workload-automation/commit/e5ed64d8d5f247eaf3374daf9e1c975b1c61c519. You probably still have a stray `.pyc` file with the old name. Depending on your installation method, it would likely be under `/usr/local/lib/python2.7/dist-packages/wa/instruments/trace-cmd.pyc` or in the analogous location in your source. Please delete the `.pyc` file to resolve the issue.

Thanks @setrofim.  Now I can confirm the rt-app issue has been fixed
in latest WA 3.0.  Thanks a lot, guys!
