### ISSUE TITLE
Apk workloads: run available version  if not specified

### ISSUE THREAD

**Issue by setrofim** [ARM-software/workload-automation#781]
Some Apk workloads support multiple versions of the applications. The version that is run can be configured via a parameter. Currently, the default for most workloads is to run the latest supported version. 

To make it more convenient for the common use case where the user wants to run the one specific version they already have (e.g. they were running what was the latest at the time, however WA's automation has since updated to a later version), change the default behaviour so that, if a version is not explicitly specified, discover which version is available on the system, and run that.

**Comment by marcbonnici** [comment]
Implemented by https://github.com/ARM-software/workload-automation/pull/947
