### ISSUE TITLE
Question: Can we specify a remote file on the exoplayer workload agenda for 'filename' ?

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#811]

**Comment by setrofim** [comment]
Yes, as is clearly stated in `exoplayer` documentation (viewable with `wa show exoplayer`)

> The name of the video file to play.  This can be either a path to the file anywhere on  your  file system, or it could be just a name, in which case, the workload will look for  it  in  /home/setrofim/.workload_automation/dependencies/exoplayer

**Comment by setrofim** [comment]
If by "remote" you mean a URL of a file to be downloaded, then no. You'll need to download it first and then specify the path to it.

**Comment by dlezcano** [comment]
Sorry I should have elaborate a bit. I meant a *remote* file for example:
https://<myurl>/myvideo
ssh://<myaddress>/myvideo
?

**Comment by setrofim** [comment]
Yes, sorry, I misinterpreted the "remote" part in my original response. No, `exoplayer` does not down load the file.

**Comment by dlezcano** [comment]
Thanks. Actually I'm interested in doing 'streaming' video rendering benchmarking for youtube. I thought, as exoplayer seems to use the same backend, we could use it to mimic a youtube streaming.

**Comment by dlezcano** [comment]
exoplayer description says:
"It provides an alternative to Android’s MediaPlayer API for playing audio and video both locally and over the Internet"

**Comment by setrofim** [comment]
`exoplayer` is specifically a non-streaming local video playback. If you want streaming, there is the `youtube_playback` workload which does take a video URL as a paramter.

**Comment by dlezcano** [comment]
Excellent! Thanks !
