### ISSUE TITLE
WA3: Error 'Connected but Android did not fully boot.'

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#812]
Hi,
when trying to run any workload I get the error:
ERROR    Connected but Android did not fully boot.

Any clue on what it could be ?

Thanks

**Comment by Sticklyman1936** [comment]
When connecting to an Android device, devlib checks to see if Android has set the "sys.boot_completed" property within a specified timeout (default seems to be 10 seconds, but WA may override that). If the timeout is reached before the flag is set, then you get the above error.

I would try and leave the device for a bit longer after rebooting it before connecting to it. There is a chance we need to increase the timeout if that is causing issues.

Which device and Android version are you using?

**Comment by dlezcano** [comment]
My Android is booted since 39 minutes and I don't have the "sys.boot_completed" property.
The version is Q.

**Comment by setrofim** [comment]
`sys.boot_completed` is used to indicate that Android is fully booted. So one of two things is possible, either

a) You system has not fully booted (the fact it has reached home screen and allows to launch apps is not an indication of that).  If it hasn't booted in 39 minutes, it probably never will. This will indicate some issue with Android runtime -- check logcat and dmesg output from the device, it's possible some service is failing to launch.

b) `sys.boot_completed` was removed in Q. In which case, I would expect there ought to be some alternative means of detecting boot completion.

**Comment by dlezcano** [comment]
I checked logcat and dmesg and there are indeed a lot of fails resulting from the tombstoned crashing.
I'll try to run an Android without error and come back to close this issue if sys.boot_completed appears and solves the issue.
Thanks for your quick answer.
