### ISSUE TITLE
WA3: applaunch stays stuck

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#850]
Hi dear wlauto team,

I'm trying to run the applaunch workload. I installed the gmail and gphoto apk and started the applaunch workload with the simple command : wa run applaunch

As nothing happens after 30 minutes, I aborted the workload.

INFO     Running job wk1
INFO         Configuring augmentations
INFO         Configuring target for job wk1 (applaunch) [1]
INFO         Setting up job wk1 (applaunch) [1]
INFO     Got CTRL-C. Aborting.
INFO         Completing job wk1
INFO     Job completed with status ABORTED

Am I missing something ? Thanks in advance.

Attached run.log

[run.log](https://github.com/ARM-software/workload-automation/files/2162742/run.log)

**Comment by marcbonnici** [comment]
Hello,

Looking at the log it appears to be getting stuck when attempting to launch the gmail application. Can you confirm whether gmail managed to launch and are you able to open it manually?

**Comment by dlezcano** [comment]
My board does not have a HDMI output plugged in. I'll do the setup and come back with the answer.

**Comment by marcbonnici** [comment]
Assuming no longer relevant. Please re open if this is not the case.
