### ISSUE TITLE
PCMark UI error

### ISSUE THREAD

**Issue by johnny90** [ARM-software/workload-automation#889]
Hello,

When running WA from Lisa, PCMark crashes at every iteration with the following error:
[run.log](https://github.com/ARM-software/workload-automation/files/2283547/run.log)

I'm running WA 3.0.0 on a Pixel 2 device with Android 8.1.

Any suggestions on how to fix this ? Thank you in advance.

**Comment by marcbonnici** [comment]
Hello,

Would you be able to tell me the version of PCMark you are using and could you also send me the captured .png and .uix file (which should be located in the __failed/<workload> directory)? 

Thanks

**Comment by johnny90** [comment]
I am using PCMark 2.0. Below is the zip with the two files.

[pcmark-capture.zip](https://github.com/ARM-software/workload-automation/files/2287278/pcmark-capture.zip)

Thank you!

**Comment by marcbonnici** [comment]
Thanks for providing them, it looks like the device is still determine whether the tests are installed or not at this particular stage. 
If you launch the app manually could you tell me what the "Work 2.0 Initializing" text changes to once it's finished loading?

**Comment by johnny90** [comment]
It remains there, and the orange install button does not appear even when I launch the app manually.

**Comment by marcbonnici** [comment]
Ah I see. So it seems like it is a problem with the app itself, could you try uninstalling it completely and reinstalling to see if that allows it to load correctly?

**Comment by johnny90** [comment]
I did that just now, plus rebooting the device, and it still doesn't load correctly

**Comment by marcbonnici** [comment]
Hmm.. Could you confirm the exact version of the apk you are using? For reference the one I am testing with is v2.0.3716.

**Comment by johnny90** [comment]
I have the same apk, 2.0.3716

**Comment by johnny90** [comment]
The device is connected to the network, I think it is also visible in the png capture from before

**Comment by marcbonnici** [comment]
Does the network have internet access? / Do other apps on the device work correctly?

**Comment by johnny90** [comment]
Yes, other apps behave as expected. I just reverted back to PCMark v1.3.3083 and it is stuck in the same state, however this one displays a device unrecognizable message on the 'my device' tab

**Comment by marcbonnici** [comment]
Is there anything running on the device that could be interfering with the app / its internet connectivity in the background?

**Comment by johnny90** [comment]
No, nothing is interfering with the app. The only thing could be that other tests are run with airplane mode enabled, but for PCMark I enabled back the network access.

**Comment by marcbonnici** [comment]
Could you try leaving airplane mode off, checking the web browser works correctly etc and then launching the app manually to see if that could be the cause of the problem?

**Comment by johnny90** [comment]
I attempted that. Other apps work correctly (browser, youtube etc.), but PCMark keeps hanging in all scenarios. I also flashed a new kernel and the result is still the same

**Comment by marcbonnici** [comment]
Hmm.. I'm sorry I have not managed to recreate that issues on any of our devices here so I'm not really sure what to suggest really apart from maybe try contacting the developers of PCMark to see if they have any further ideas?

**Comment by johnny90** [comment]
I'll continue to investigate, thank you very much for your time

**Comment by setrofim** [comment]
Assuming no longer relevant.
