### ISSUE TITLE
wa3: AttributeError('module' object has no attribute 'getfullargspec')

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#895]
Hi,

I'm trying to run the jankbench workload with the master/HEAD for workload-automation and devlib (both were installed with sudo pip -h install ./devlib ./workload-automation
When I run the jankbench workload, this one fails with:

ERROR      File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 377, in execute
ERROR        self.do_execute(context)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wa/framework/execution.py", line 420, in do_execute
ERROR        instrumentation.install(instrument, context)
ERROR      File "/usr/local/lib/python2.7/dist-packages/wa/framework/instrument.py", line 327, in install
ERROR        argspec = inspect.getfullargspec(attr)
ERROR    
ERROR    AttributeError('module' object has no attribute 'getfullargspec')

any idea of what it could be ?

**Comment by marcbonnici** [comment]
Hi,
This appears to be a compatibility issue between Python 2 and 3. I've submitted a PR  https://github.com/ARM-software/workload-automation/pull/896. that should address the problem.

Would you be able to let me know if this fixes your issue?

**Comment by dlezcano** [comment]
Yes, it does !
Thanks a lot for your quick fix.
  -- Daniel
