### ISSUE TITLE
Set kernel debug value in sysfs fail

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#897]
Hi dear WA team,

I'm trying to set the value in my agenda for /sys/kernel/debug/sched_feat but that fails with the error:

ERROR        Could not set the value of /sys/kernel/debug/sched_features to "NO_ENERGY_AWARE" (read "GENTLE_FAIR_SLEEPERS START_DEBIT NO_NEXT_BUDDY LAST_BUDDY CACHE_HOT_BUDDY WAKEUP_PREEMPTION NO_HRTICK NO_DOUBLE_TICK LB_BIAS NONTASK_CAPACITY TTWU_QUEUE NO_SIS_AVG_CPU SIS_PROP NO_WARN_DOUBLE_CLOCK RT_PUSH_IPI RT_RUNTIME_SHARE NO_LB_MIN ATTACH_AGE_LOAD WA_IDLE WA_WEIGHT WA_BIAS UTIL_EST NO_ENERGY_AWARE EAS_PREFER_IDLE FIND_BEST_TARGET FBT_STRICT_ORDER NO_SCHEDTUNE_BOOST_HOLD_ALL")

**Comment by marcbonnici** [comment]
Hi,

Whenever WA attempts to write to a sysfs node it will by default read back the node to check it has been written correctly. 
If this node does not echo back only the value that was written you can disable this verification by appending a `!` to the path e.g.

`/sys/kernel/debug/sched_feat!: NO_ENERGY_AWARE`

**Comment by dlezcano** [comment]
Ah, excellent.  Thanks!
