### ISSUE TITLE
WA3 is stuck when running multiple test on the jankbench workload

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#901]
After fixing the issue 898 with 'logcat -c', I was able to run the simple jankbench workload provided in the issue. However when running a more complex one (in attachment), the test run stays stuck.
There is a 'logcat' instance waiting for a message on the guest.

[jankbench.yaml.gz](https://github.com/ARM-software/workload-automation/files/2367636/jankbench.yaml.gz)

**Comment by marcbonnici** [comment]
Hi, 
I ran your attached agenda on my hikey board however didn't encounter any errors. 
Would you be able to send me your run.log with the included error as well?

**Comment by dlezcano** [comment]
Hi Marc,

sorry for the delay, I was out of the office and got my remote server stuck.

Here is the result you asked.
[run.log](https://github.com/ARM-software/workload-automation/files/2433249/run.log)

**Comment by marcbonnici** [comment]
Hi,

No problem at all. Could you please check that you are using the latest version of WA including the fixes https://github.com/ARM-software/workload-automation/issues/900 for these runs? Looking at your run log the 2 logcat commands are different which should not be the case now the calls are standardized. 
```
 878 2018-09-05 18:27:48,613 DEBUG       android:         adb -s 6FFA6A4E018D7CC5 logcat -c
 879 2018-09-05 18:27:58,666 DEBUG       android:         adb -s 6FFA6A4E018D7CC5 shell dumpsys power
 880 2018-09-05 18:27:58,757 DEBUG       android:         adb -s 6FFA6A4E018D7CC5 shell logcat -c
```

**Comment by dlezcano** [comment]
Ah, right. Actually it is because it is not the right run.log. My script rely on adb shell "uname -r" to build the output path but in this case sometimes the adb command fails and the output ends up in the wrong place.

Here is the latest one.

[run.log](https://github.com/ARM-software/workload-automation/files/2434156/run.log)

I noticed there is an adb instance stuck and another one zombie.

dlezcano 16986  5094  0 15:37 pts/9    00:00:00  |                       \_ /bin/bash ./wa_run jankbench
dlezcano 16992 16986 27 15:37 pts/9    00:02:52  |                           \_ /usr/bin/python /usr/local/bin/wa run -f -d /var/www/wa_output//4.14.67-00633-g20ebc74/jankbench /home/dlezcano/ProductCodeline/product-codeline/wlauto/agendas/jankbench.yaml
dlezcano 17301 16992  0 15:37 pts/9    00:00:00  |                               \_ [adb] <defunct>


ps -ef | grep adb
dlezcano 15339     1  0 09:41 ?        00:00:56 adb -L tcp:5037 fork-server server --reply-fd 4
dlezcano 17884 16992  0 15:48 pts/9    00:00:00 adb -s 6FFA6A4E018D7CC5 logcat
dlezcano 17885 16992  0 15:48 pts/9    00:00:00 [adb] <defunct>

**Comment by dlezcano** [comment]
If I call in another shell: adb logcat -c, that unblocks the tests

**Comment by dlezcano** [comment]
... and then it blocks again ... (added updated run.log)
[run.log](https://github.com/ARM-software/workload-automation/files/2434218/run.log)

**Comment by marcbonnici** [comment]
Ah ok, UiAutomator is not used as part of this workload so the logcat clear in BaseUiAutomation should not be the problem here.  
During the workload execution there is a monitor that waits for a specific line to know when the benchmark is finished which would explain the second adb instance that remains open, however does that close itself when the workload has finished? 

Also, where abouts does the workload get stuck on the 2nd iteration? Looking at the log it appears to launch successfully so is it just failing to detect the second time it finishes?

**Comment by dlezcano** [comment]
> During the workload execution there is a monitor that waits for a specific line to know when the benchmark is finished which would explain the second adb instance that remains open, however does that close itself when the workload has finished?

How can I know that ? Is there a trace or somethnig I can look for ?

> Also, where abouts does the workload get stuck on the 2nd iteration? Looking at the log it appears to launch successfully so is it just failing to detect the second time it finishes?

That is my feeling too

**Comment by dlezcano** [comment]
Apparently it is not necessarly at the second run, it can happen after:

INFO     Ran a total of 50 iterations: 45 SKIPPED, 1 FAILED, 4 OK

**Comment by marcbonnici** [comment]
> How can I know that ? Is there a trace or somethnig I can look for ?

This is done externally on the host and doesn't record anything so I think the best way would be to check how you have been chekcing for the adb process once the run has ended.

So I've found that the logcat monitor didn't seem to be exiting correctly on my machine potentially leaving the connection open so wondering if that could be causing your issue. Would you be able to try this patch that kills the process before exiting to see if that affects the behaviour you're seeing? 
[jankbench_test.patch.zip](https://github.com/ARM-software/workload-automation/files/2434823/jankbench_test.patch.zip)

**Comment by dlezcano** [comment]
Unfortunately, it does not change the behavio :(

**Comment by dlezcano** [comment]
I rebooted my server and tried to reproduce the issue but now it is working well without getting stuck. I'm right suspecting an issue with my USB3 hub (or a kernel issue). Let me see if I can narrow down this.

**Comment by dlezcano** [comment]
Is it possible you check if running the workload with the console opened in Android (no adb shell but minicom/something else) triggers the issue on your side ?

**Comment by marcbonnici** [comment]
I've tried replicating this however it still seems to be working correctly for me..

In the console are you interacting with logcat in anyway?  and does it work correctly if you do not have any other consoles open?

**Comment by dlezcano** [comment]
Thanks for testing on your side.

I do nothing in the console, just sometime do a top to see what happens, nothing else. It seems like it works correctly when no console is opened.

My host having the usb plugged with the board has errors on its dmesg:
pl2303 ttyUSB2: usb_serial_generic_read_bulk_callback - urb stopped: -32

After searching around, I found this message comes when the peer is not answering anymore. It is not the first time I'm seeing this and probably it comes from a problem with the hardware, perhaps with the hikey960 board where the console is plugged on the serial-usb dongle and the USB3 on the USB-C.

Is it possible to share your setup for the record ?

At this point, it is unclear where the problem comes but very likely I think it is related to this urb stopped message.

May be we can close this issue and reopen it later in case ?

**Comment by marcbonnici** [comment]
No problem. That seems to be an interesting problem however I do not have those messages appearing for me so that could be the cause. 

I have tried 2 hikey960 boards each running ASOP Android O connected over the USB-C connector and I have one with the UART serial mezzanine board connected over usb for console access.

And yea sure, please let me know if you make any progress with this.

**Comment by dlezcano** [comment]
The mezzanine board is this one?
https://www.96boards.org/product/sensors-mezzanine/
not this one?
https://www.96boards.org/product/uartserial/

Right ?

(I have the uartserial).

**Comment by marcbonnici** [comment]
Ah no sorry I meant the uartserial one.

**Comment by dlezcano** [comment]
Ok, thanks for the info.
Let's close the issue as it seems to be related to hw problems.
Thanks for your time.
