### ISSUE TITLE
Failing to run androbench

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#909]
Androbench installed version is:
package: name='com.andromeda.androbench2' versionCode='14' versionName='4.1' platformBuildVersionName='5.1.1-1819727'

If I try to run it with the following command:
   wa run androbench

I get:

INFO         Running job wk1 (androbench) [1]
ERROR            Timed out: ['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(am instrument -w -r -e markers_enabled bsFalse -e workdir ss/sdcard/devlib-target -e package_name sscom.andromeda.androbench2 -e class com.arm.wa.uiauto.androbench.UiAutomation#runWorkload com.arm.wa.uiauto.androbench/android.support.test.runner.AndroidJUnitRunner); echo "\n$?"']
ERROR            OUTPUT:
ERROR            INSTRUMENTATION_STATUS: class=com.arm.wa.uiauto.androbench.UiAutomation
ERROR            INSTRUMENTATION_STATUS: current=1
ERROR            INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
ERROR            INSTRUMENTATION_STATUS: numtests=1
ERROR            INSTRUMENTATION_STATUS: stream=
ERROR            com.arm.wa.uiauto.androbench.UiAutomation:
ERROR            INSTRUMENTATION_STATUS: test=runWorkload
ERROR            INSTRUMENTATION_STATUS_CODE: 1
ERROR            
ERROR            
ERROR        Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(echo \'echo TRACE_MARKER_STOP > \'\\\'\'/sys/kernel/debug/tracing/trace_marker\'\\\'\'\' | su); echo "\n$?"']' returned non-zero exit status 1
INFO         Processing output for job wk1 (androbench) [1]
INFO             Processing using "csv"
INFO         Tearing down job wk1 (androbench) [1]
ERROR            Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(am instrument -w -r -e markers_enabled bsFalse -e workdir ss/sdcard/devlib-target -e package_name sscom.andromeda.androbench2 -e class com.arm.wa.uiauto.androbench.UiAutomation#teardown com.arm.wa.uiauto.androbench/android.support.test.runner.AndroidJUnitRunner); echo "\n$?"']' returned non-zero exit status 1
ERROR            Error in instrument trace-cmd
ERROR            Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(rm -rf "/sdcard/devlib-target/trace.dat"); echo "\n$?"']' returned non-zero exit status 1
ERROR        Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(ls /); echo "\n$?"']' returned non-zero exit status 1
INFO         Completing job wk1
ERROR    Job wk1 iteration 1 completed with status FAILED. Max retries exceeded.
ERROR    Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(ls /); echo "\n$?"']' returned non-zero exit status 1
ERROR    Skipping remaining jobs due to "Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(ls /); echo "\n$?"']' returned non-zero exit status 1".
INFO     Run completed
INFO         Finalizing job wk1 (androbench) [1] 
ERROR            Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(pm list packages); echo "\n$?"']' returned non-zero exit status 1
INFO     Done.
INFO     Run duration: N/A
INFO     Ran a total of 1 iterations: 1 FAILED
INFO     Results can be found in wa_output
WARNING  There were errors during execution.
WARNING  Please see wa_output/run.log

Attached the run.log
[run.log](https://github.com/ARM-software/workload-automation/files/2438520/run.log)

**Comment by marcbonnici** [comment]
The known working version for our androbench workload is 5.0.1. Due to the major version bump from 4.1 I suspect the two versions will not be compatible. Would you be able to try a newer version?

**Comment by dlezcano** [comment]
I tried the version 5.0.1 but I get a different error (not pasting it) but added the run.log.
[run.log](https://github.com/ARM-software/workload-automation/files/2441982/run.log)

**Comment by marcbonnici** [comment]
Ah ok so it appears to be failing part way extracting the results for that one, would you be able to send me the "run-error" screencapture and uix dump from the failed job output directory?

**Comment by dlezcano** [comment]
![output-error](https://user-images.githubusercontent.com/5495388/46411758-e2a0c980-c71c-11e8-9a24-f179e85a1d84.png)

[output-error.uix.gz](https://github.com/ARM-software/workload-automation/files/2442079/output-error.uix.gz)

**Comment by marcbonnici** [comment]
Thank you, I've submitted a PR https://github.com/ARM-software/workload-automation/pull/910 which should allow the results screen to scroll to view the remaining scores. 
Would you be able to see if that fixes your issue?

**Comment by dlezcano** [comment]
Yes, it does !! :+1: 

Thanks a lot
