### ISSUE TITLE
Error in instrument trace-cmd

### ISSUE THREAD

**Issue by dlezcano** [ARM-software/workload-automation#959]
When running my agenda, I have randomly the error making the entire tests to fail. I have no idea of the reason of the failure.

2019-02-22 15:07:01,839 ERROR    instrument:         Error in instrument trace-cmd
2019-02-22 15:07:01,841 DEBUG        signal:         Sending error-logged from <wa.utils.log.ErrorSignalHandler object at 0x7f0513e00510>
2019-02-22 15:07:01,841 DEBUG        signal:         Disconnecting <bound method Executor._error_signalled_callback of executor> from error-logged(<Sender: Any>)
2019-02-22 15:07:01,841 ERROR    instrument:         Got exit code 969696
2019-02-22 15:07:01,841 ERROR    instrument:         from target command: echo '/data/local/tmp/bin/trace-cmd start -e sched* -e irq* -e power* -e thermal*' | su
2019-02-22 15:07:01,841 ERROR    instrument:         OUTPUT:
2019-02-22 15:07:01,842 DEBUG       android:         adb -s 6FFA6A4E018D7CC5 shell ls /
2019-02-22 15:07:01,853 DEBUG        signal:         Sending after-workload-execution from default-wk2 (idle) [1]
2019-02-22 15:07:01,853 DEBUG       android:         adb -s 6FFA6A4E018D7CC5 shell echo 'echo TRACE_MARKER_STOP > /sys/kernel/debug/tracing/trace_marker' | su
2019-02-22 15:07:01,860 DEBUG        signal:     Sending error-logged from <wa.utils.log.ErrorSignalHandler object at 0x7f0513e00510>
2019-02-22 15:07:01,860 DEBUG        signal:     Disconnecting <bound method Executor._error_signalled_callback of executor> from error-logged(<Sender: Any>)
2019-02-22 15:07:01,859 ERROR        runner:     Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(echo \'echo TRACE_MARKER_STOP > /sys/kernel/debug/tracing/trace_marker\' | su); echo "\n$?"']' returned non-zero exit status 1
2019-02-22 15:07:01,861 DEBUG       android:     adb -s 6FFA6A4E018D7CC5 shell ls /
2019-02-22 15:07:01,871 DEBUG        signal:     Sending before-job-output-processed from runner

**Comment by marcbonnici** [comment]
```Exit code 969696``` is the error code that we generate in devlib if we get no response from the device. This usually occurs the device is disconnected or has crashed, could you confirm if the device is still seen by the host and is responsive after this error occurs?

**Comment by dlezcano** [comment]
Yes, I confirm I still can access the board.

**Comment by marcbonnici** [comment]
Can you try running the failing command manually and seeing what output it produces?

**Comment by dlezcano** [comment]
When the error appeared I gave a try and the command succeed. Now I'm trying to reproduce the issue after an update of devlib and workload-automation and I get the error:
ERROR    ('CONFIG_SND_SOC_PCM512X_SPI is not exposed in kernel config', u'CONFIG_SND_SOC_PCM512X_SPI')
Is there something I missed ?

**Comment by marcbonnici** [comment]
This is something that can happen when your devlib and WA version become out of sync. Can you please delete your ```~/.workload_automation/cache/targets.json``` (or equivalent)?

**Comment by dlezcano** [comment]
Ok, yes that fixed the CONFIG problem. So I reproduce the error and tried the command after the error happened, I'm not sure it is correct:
adb -s 6FFA6A4E018D7CC5 shell '(echo \'echo TRACE_MARKER_STOP > /sys/kernel/debug/tracing/trace_marker\' | su); echo "\n$?"'
bash: syntax error near unexpected token `)'

**Comment by marcbonnici** [comment]
That looks like it might just be an error introduced in the the copy/pasting.
Could you open a shell on the device, enter ```su``` and then execute the command directly ```echo TRACE_MARKER_STOP > /sys/kernel/debug/tracing/trace_marker```?

Can you also send me your run.log to see if there is something else going on before this?

**Comment by dlezcano** [comment]
Yes, that is what I did initially and it worked. I did it again and worked again.

[run.log](https://github.com/ARM-software/workload-automation/files/2894546/run.log)

**Comment by marcbonnici** [comment]
Thank you, everything else looks like it should be ok..

What was the output when you ran the command? 
And also does the workload execute successfully if the `trace-cmd` instrument is disabled?

**Comment by dlezcano** [comment]
There is no output, the command writes a tag in the pseudo-filesystem
The trace-cmd instrument is not enabled, I have:

global:
  # Collect energy data, ftrace files, and dmesg
  # You may want to edit your config.yaml to set up the energy_measurement
  # instrument (an example configuration is provided in this repo).
  instrumentation: [energy_measurement, dmesg]
  iterations: 3

  # To aid reproducibility and try to reduce noise in power measurements,
  # minimise the screen brightness and set airplane mode on.
  runtime_params:
    brightness: 0
    screen_on: true
    airplane_mode: true
    sysfile_values:
        /dev/stune/foreground/schedtune.boost: 20
        /dev/stune/top-app/schedtune.boost: 20

  energy_measurement:
    instrument: arm_energy_probe
    instrument_parameters:
        config_file: "/home/dlezcano/arm-probe/config-aep-hikey960"

**Comment by marcbonnici** [comment]
The command executes successfully and does not return an error code? 

Also your `run.log` indicates that you have `trace-cmd` enabled in your global config file. 
Could you either temporarily remove that or add ` --disable trace-cmd ` to you wa command line and see if that runs ok to help narrow the problem down?

**Comment by dlezcano** [comment]
Yes, the command executes successfully and the error code is 0.

I had the trace-cmd instrumentation in my global WA configuration file, I disabled it.

Now when I run the workload I have:

ERROR            Got exit code 969696
ERROR            from target command: sleep 15
ERROR            OUTPUT:
ERROR            Error in instrument dmesg
ERROR            Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(echo dmesg | su); echo "\n$?"']' returned non-zero exit status 1
ERROR        Command '['adb', '-s', '6FFA6A4E018D7CC5', 'shell', '(ls /); echo "\n$?"']' returned non-zero exit status 1

**Comment by dlezcano** [comment]
Mmh, I think the problem is coming from the autosuspend. The screen off option is set for the different workload and disabling it seems to fix the problem (will figure out in a couple of hours when the tests finish).

**Comment by marcbonnici** [comment]
If `sleep` is now presenting the issue then that would make sense that it was something stopping the board from responding to WA.

**Comment by dlezcano** [comment]
Right. Wouldn't make sense to have WA3 to setup the board. May be the adb port can be a wakeup source?

**Comment by marcbonnici** [comment]
WA currently does support performing an initial configuration including setting the screen state and we recommend manually setting the screen timeout to be as long as possible which should keep the device awake. 
When the screen is turned off however this should not cause the device to stop responding to adb commands. If this is the case for your device I am not currently aware of a way to wake it up again. Did you have something particular in mind as you can use WA to set arbitrary sysfs nodes if there is a particular way to configure this on the device?

**Comment by dlezcano** [comment]
Can something like:
adb shell input keyevent KEYCODE_WAKEUP
work ?

**Comment by marcbonnici** [comment]
I'm not sure it would, if by the time the error occurs it is already not responding to adb commands whether this would affect the device?
Also if it did then this would turn on the screen on so would it not make sense to just keep the screen on throughout the test?

**Comment by dlezcano** [comment]
Actually I don't know. When my tests finish, I will give a try.

**Comment by setrofim** [comment]
Is this still relevant?

**Comment by dlezcano** [comment]
It is still relevant but I don't know how to fix it properly. I think the platform can be setup so the adb can be a wakeup source but not sure that works for all platform neither a WA3 needs a change.

**Comment by marcbonnici** [comment]
This sounds like a more device specific issue and there is nothing obvious we can do in WA to prevent this. Closing the issue for now.
