### ISSUE TITLE
[revet] replay revent error - ERROR: Could not read devices: Input/output error

### ISSUE THREAD

**Issue by billccchang** [ARM-software/workload-automation#972]
Hi there,
I tried to replay my record revent. 
However, it showed error:
Dose anyone know this error cause?
Thanks~!

INFO     Setting up target
INFO     Pushing file to target
INFO     Starting replay
ERROR    Got exit code 1
ERROR    from target command: /data/local/tmp/bin/revent replay /sdcard/wa-working/xxx_64_bsp.revent
ERROR    OUTPUT: ERROR: Could not read devices: Input/output error
ERROR    

Best,
Bill

**Comment by marcbonnici** [comment]
Hi Bill,

Did you manage to perform the recording without any issues?

If you have a superuser access app, could you check whether any attempts to gain root access were denied? And also could you rerun the command with the `-v` argument and post the last the few lines of the output?

Thanks

**Comment by setrofim** [comment]
Assuming no longer relevant, as OP hasn't responded.
